### ISSUE TITLE
No support for UDP

### ISSUE THREAD

**Issue by danlsgiga** [mholt/caddy-l4#10]
As I'm giving `caddy-l4` a try to a tentative hacky ingress gateway in my homelab, I tried to have it proxying DNS UDP but as soon as I give the `listen` address `"udp/127.0.0.1:5000"`, caddy fails to start with the following error:

`run: loading initial config: loading new config: layer4 app module: start: listen udp 127.0.0.1:5000: address 127.0.0.1:5000: unexpected address type`

**Comment by francislavoie** [comment]
Can you post your full JSON, to replicate?

**Comment by danlsgiga** [comment]
yup...

here it goes:

```json
{
  "apps": {
    "layer4": {
      "servers": {
        "example": {
          "listen": [
            "udp/127.0.0.1:5000"
          ],
          "routes": [
            {
              "match": [
                {
                  "ip": {
                    "ranges": [
                      "192.168.1.0/24",
                      "127.0.0.1"
                    ]
                  }
                }
              ],
              "handle": [
                {
                  "handler": "proxy",
                  "upstreams": [
                    {
                      "dial": [
                        "192.168.1.10:53"
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      }
    }
  }
}
```

**Comment by danlsgiga** [comment]
Ah, just a note... I wanted to validate the proxy actually works in this scenario... for that I used `dig +tcp @127.0.0.1 -p 5000 google.com` when caddy is running over TCP

**Comment by mholt** [comment]
Thanks for the report. :man_facepalming:  Totally forgot about this for some reason. In my testing, 4689395265dee71a3222ea2347862485fac04cfb does the trick with your config (except I'm using a simple echo server). Let me know if you encounter any more problems. Remember that you can't do some things with UDP like you can with TCP.

**Comment by danlsgiga** [comment]
Owww... that was fast! Thanks tons!!
