### ISSUE TITLE
UDP example

### ISSUE THREAD

**Issue by vtacquet** [mholt/caddy-l4#12]
Hi Matt,

Do you have an example of a json config with UDP proxy ?

Thanks
Vincent

**Comment by mholt** [comment]
Same as the TCP example from the README, except with UDP addresses, I would imagine?

```json
{
	"apps": {
		"layer4": {
			"servers": {
				"example": {
					"listen": ["udp/127.0.0.1:5000"],
					"routes": [
						{
							"handle": [
								{
									"handler": "proxy",
									"upstreams": [
										{"dial": ["udp/localhost:5001"]}
									]
								}
							]
						}
					]
				}
			}
		}
	}
}
```

Haven't tested this. See if that works.

**Comment by vtacquet** [comment]
thx, well for tcp it works without the tcp/ in front and I didn't saw it anywhere in the documentation, I only tried with /udp at the end (docker syntax)
![image](https://user-images.githubusercontent.com/5128967/103456725-2bc79580-4cf9-11eb-9640-bd88e5a1cac1.png)

**Comment by mholt** [comment]
https://caddyserver.com/docs/conventions#network-addresses
