### ISSUE TITLE
[Question] Replicating what Stunnel does but with caddy-l4

### ISSUE THREAD

**Issue by alphajoza** [mholt/caddy-l4#124]
I know that you are in [Caddy community](https://caddy.community/) but thought putting the link here is maybe more appropriate.

Check [here](https://caddy.community/t/replicating-what-stunnel-does-but-with-caddy-l4) please.

I want to tunnel SSH traffic over TLS with the help of caddy-l4 (I’m using a virtual machine (Ubuntu 20.04) which is hosted in a Windows 10 setup)

I want to SSH into Ubuntu virtual machine from Windows 10;

My config.json in Ubuntu virtual machine:
**A TCP reverse proxy that terminates TLS on 443 and proxies to SSH server on port 22**
```
{
	"apps": {
		"layer4": {
			"servers": {
				"example": {
					"listen": [
						"192.168.1.11:443"
					],
					"routes": [
						{
							"handle": [
								{
									"handler": "tls"
								},
								{
									"handler": "proxy",
									"upstreams": [
										{
											"dial": [
												"localhost:22"
											]
										}
									]
								}
							]
						}
					]
				}
			}
		},
		"tls": {
			"certificates": {
				"automate": ["192.168.1.11"]
			},
			"automation": {
				"policies": [
					{
						"issuers": [{"module": "internal"}]
					}
				]
			}
		}
	}
}
```

My Problem is in config.json of Windows 10 machine:
**A config that tunnels the received SSH traffic on port 22000 over TLS and sends it to 192.168.1.11:443**
```
{
	"apps": {
		"layer4": {
			"servers": {
				"example": {
					"listen": [
						"localhost:22000"
					],
					"routes": [
						{
							"handle": [
								{
									??? What should I put here ???
								}
							]
						}
					]
				}
			}
		},
		"tls": {
			"certificates": {
				"automate": [
					"localhost"
				]
			},
			"automation": {
				"policies": [
					{
						"issuers": [
							{
								"module": "internal"
							}
						]
					}
				]
			}
		}
	}
}
```

**Comment by mholt** [comment]
Sorry I just saw this now. If you're simply receiving SSH traffic and you want to proxy it, wouldn't you just put a `proxy` handler there?

Or do you mean you want to add TLS to the SSH so the SSH is proxied inside TLS to `192.168.1.11:443`?

**Comment by mholt** [comment]
To add TLS when proxying, simply configure TLS in the upstream (around "dial" and such):

https://github.com/mholt/caddy-l4/blob/4e8aaac4658109e314b8d7bba13fe7578b3471ca/modules/l4proxy/upstream.go#L31-L37

Hope that helps!
