### ISSUE TITLE
MQTT

### ISSUE THREAD

**Issue by Axelgoris99** [mholt/caddy-l4#129]
Heeeeey, sorry to bother you!
thanks for the great work.

is it possible to use this to handle mqtt connection? I'm pretty new to this and I know nothing :(
Have a lovely day, 
Axel

**Comment by mholt** [comment]
There's no special handling for MQTT in this repo, but it could be added... This module is very extensible. Feel free to contribute if you'd like!

**Comment by Axelgoris99** [comment]
I'm definitely down for it but being quite a beginner in this field, I probably need to learn quite a lot about servers and layers first!
Any good suggestions/things to read/build to understand all of this ?

**Comment by mholt** [comment]
I would start with learning about what TCP is and how it works. (I had to implement it in college. That was fun! And a lot of work.)

Then if you don't know Go, it's a pretty easy language to learn if you're already a programmer, esp. if you're familiar with C or similar: https://go.dev/tour/welcome/1

Then I can show you some code here you could use as an example.

**Comment by Axelgoris99** [comment]
Alright, awesome, I'll try to give it some time!
Can't promise but if i can deliver, I definitely will :)
Have an amazing night!
Thanks a lot.
