### ISSUE TITLE
Supports HAProxy PROXY protocol in handler

### ISSUE THREAD

**Issue by mildred** [mholt/caddy-l4#13]
It allows to keep the source address over any kind of protocol:

https://www.haproxy.com/blog/haproxy/proxy-protocol/

It is supported for example by Exim:

https://exim.org/exim-html-4.93/doc/html/spec_html/ch-proxies.html

**Comment by francislavoie** [comment]
This plugin adds PROXY protocol support: https://github.com/mastercactapus/caddy2-proxyprotocol

**Comment by mildred** [comment]
I was thinking that Caddy would be a PROXY client. For example it will listen to any TCP socket, could do TLS terminaison (using Let's Encrypt) and forward the  connection to a backend over the PROXY protocol (use case: Exim)

The plugin you are referring to seems to be doing PROXY server (the other way around, Caddy being forwarded from another front reverse-proxy)

**Comment by francislavoie** [comment]
Ah, that does make sense. Thanks for explaining.

**Comment by mholt** [comment]
Sure, pull requests welcomed!

**Comment by mildred** [comment]
@mholt  What would the configuration you would suggest for such a feature?

**Comment by mildred** [comment]
I would see it as an option to the proxy handler, something like:

```json
							"handle": [
								{
									"handler": "proxy",
									"proxy_header": "v1",
									"upstreams": [
										{"dial": ["localhost:80"]}
									]
								}
							]
```

**Comment by francislavoie** [comment]
Might be better implemented as a separate handler that prepends some bytes to the connection before the proxy starts copying it to the upstream. I'm not totally certain how that would look but it seems like it should be possible looking at https://github.com/mholt/caddy-l4/blob/master/layer4/connection.go

**Comment by mildred** [comment]
From an implementation point of view, it seems like it would duplicate quite some code

**Comment by lxhao61** [comment]
Hope to merge mildred linked a pull request, it works well.

**Comment by contrun** [comment]
@francislavoie I think https://github.com/mastercactapus/caddy2-proxyprotocol does not work the same way as the tls handler in this repo. For instance, I want to define a handler which first terminates PROXY protocol, then terminates tls, then finally forwards http traffic to the upstream. If it fails to do so, just fallback to next handler. Can we do that easily? It seems to me the handlers in this repo are much more composable, i.e. we can make them work together without much hassle. It would be great if we can have PROXY matcher and handler, just like the tls matcher and handler in this repo.
