### ISSUE TITLE
xcaddy build failed | caddy-l4@upgrade - August 2nd

### ISSUE THREAD

**Issue by whoo** [mholt/caddy-l4#134]
Hi,

There is an issue with basic integration of caddy-l4.
Probably I'm doing something wrong.
Thks 

<pre>
from caddy:builder-alpine as builder
RUN xcaddy build --with github.com/mholt/caddy-l4
FROM caddy
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
</pre>

<pre>
51.04 2023/08/03 03:21:28 [INFO] exec (timeout=-2562047h47m16.854775808s): /usr/local/go/bin/go get -d -v github.com/mholt/caddy-l4 github.com/caddyserver/caddy/v2@v2.6.4 
51.93 go: downloading github.com/mholt/caddy-l4 v0.0.0-20230801212311-9e005885acd9
53.37 go: github.com/mholt/caddy-l4@upgrade (v0.0.0-20230801212311-9e005885acd9) requires github.com/caddyserver/caddy/v2@v2.7.0-beta.2.0.20230725185021-d7d16360d411, not github.com/caddyserver/caddy/v2@v2.6.4
53.37 2023/08/03 03:21:30 [FATAL] exit status 1
------
failed to solve: process "/bin/sh -c xcaddy build --with github.com/mholt/caddy-l4" did not complete successfully: exit code: 1
</pre>

**Comment by francislavoie** [comment]
Try with `xcaddy build v2.7.1 --with github.com/mholt/caddy-l4`

The problem is that the currently latest version of the `builder` image variant sets `CADDY_VERSION=2.6.4` so it tries to use that version as the base, but `caddy-l4` now requires `v2.7.0-beta.2` at minimum.

**Comment by whoo** [comment]
hi,
It works with this quick fix 
<pre>
from caddy:2.7.0-beta.2-builder as builder
RUN xcaddy build v2.7.1 --with github.com/mholt/caddy-l4
FROM caddy
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
</pre>

Thanks
