### ISSUE TITLE
Not able to connect to database

### ISSUE THREAD

**Issue by Miggets7** [mholt/caddy-l4#136]
Hi all,

I've got this config:
```

{
  "apps": {
    "http": {
    ...
    },
    "layer4": {
      "servers": {
        "srv0": {
          "listen": [":27017"],
          "routes": [
            {
              "handle": [
                {
                  "handler": "proxy",
                  "upstreams": [{ "dial": ["10.0.22.76:27017"] }]
                }
              ]
            }
          ]
        }
      }
    }
  }
}
```

And I'm trying to connect to a MongoDB instance running in a docker swarm. That's the 10.0.22.76 ip.
But I've got no success in connecting.

I'm using the module in combination with [caddy-docker-proxy](https://github.com/lucaslorentz/caddy-docker-proxy) and [caddy-ext/layer4](https://github.com/RussellLuo/caddy-ext/tree/master/layer4).

This is the docker part:
```
labels:
        caddy.layer4.:27017.proxy: "{{upstreams 27017}}"
```

Which produces the global json part mentioned above. Am I missing something?

**Comment by mholt** [comment]
> But I've got no success in connecting.

What is the error message?

**Comment by Miggets7** [comment]
This is what mongodb compass(client app) returns, after trying for a while:
```connection <monitor> to 86.105.245.116:27017 closed```
I think it goes into timeout.

I've created a docker image with this Dockerfile:
```
ARG CADDY_VERSION=2.7.2
FROM caddy:${CADDY_VERSION}-builder AS builder

RUN xcaddy build \
    --with github.com/lucaslorentz/caddy-docker-proxy/v2 \
    --with github.com/mholt/caddy-l4/layer4 \
    --with github.com/RussellLuo/caddy-ext/layer4

FROM caddy:${CADDY_VERSION}-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

CMD ["caddy", "docker-proxy"]
```

The ports are open:
```
services:
  caddy_server:
    image: registry.stofloos.nl/caddy-server
    ports:
      - 80:80
      - 443:443
      - 27017:27017
```

The caddy server service doesn't show any error regarding the port 27017 or any another error regarding layer4. Don't if I should look in a specific place?

**Comment by francislavoie** [comment]
Enable the `debug` global option for additional logging.

**Comment by mholt** [comment]
If nothing shows up even in the debug logs, then there's a good chance the connection isn't reaching Caddy in the first place. :thinking:

**Comment by Miggets7** [comment]
After restarting the caddy server, everything started working. So I guess some sort of caching?

**Comment by mholt** [comment]
Interesting. I don't know -- maybe the config you thought was running wasn't actually running / POSTed to the server before the restart? Just a guess. I've done it before. Glad to hear it is working now though! If you can reproduce a bug I'd like to know so we can fix it :grin:

**Comment by Miggets7** [comment]
I'll keep an eye on it. Sorry for the trouble.

Out of curiosity, is this module becoming part of the default caddy server? Cause I think it would be a great addition and make caddy more complete.

**Comment by mholt** [comment]
(No worries. Definitely let me know, like if a config isn't "sticking" like you'd expect. Thanks!)

> Out of curiosity, is this module becoming part of the default caddy server? Cause I think it would be a great addition and make caddy more complete.

I agree with you. Maybe someday, but it's not ready yet. (Some bugs like #72 and #132 definitely need to be figured out first.)
