### ISSUE TITLE
how to proxy quic

### ISSUE THREAD

**Issue by New2Niu** [mholt/caddy-l4#149]
tcp proxy
```
{
   "apps": {
      "layer4": {
         "servers": {
            "srv0": {
               "listen": [":443"],
               "routes": [{
                  "match": [{
                     "tls": {
                     }
                  }],
                  "handle": [{
                     "handler": "proxy",
                     "upstreams": [{
                        "dial": ["{l4.tls.server_name}:443"]
                     }]
                  }]
               }]
            },
            "srv1": {
               "listen": [":80"],
               "routes": [{
                  "match": [{
                     "http": []
                  }],
                  "handle": [{
                     "handler": "proxy",
                     "upstreams": [{
                        "dial": ["{l4.http.host}:80"]
                     }]
                  }]
               }]
            }
         }
      }
   },
   "logging": {
      "logs": {
         "default": {
            "encoder": {
               "format": "json",
               "time_format": "wall",
               "time_local": true
            },
            "exclude": [],
            "writer": {
               "filename": "proxy.event.log",
               "output": "file",
               "roll": false
            }
         }
      }
   }
}
```
How to proxy quic by sni?
udp proxy not work:
```
 "srv11": {
     "listen": ["udp/:443"],
     "routes": [{
        "match": [{
           "tls": {
           }
        }],
        "handle": [{
           "handler": "proxy",
           "upstreams": [{
              "dial": ["{l4.tls.server_name}:443"]
           }]
        }]
     }]
  },
```

**Comment by francoismichel** [comment]
It does not seem doable right now. However, that might be quite "easily" achievable using quic-go's
[`EarlyListener`](https://github.com/quic-go/quic-go/blob/v0.41.0/server.go#L154) mechanism: we could setup an EarlyListener and feed it UDP packets. When it accepts a new conn, we could extract the SNI from its TLS context (simply access the [`ConnetionState`](https://github.com/quic-go/quic-go/blob/v0.41.0/interface.go#L339)'s TLS context that contains the SNI, everything seems correctly exposed by quic-go. It feels a bit hackish though.

Any thoughts on that ?

**Comment by mholt** [comment]
I don't know enough about the details of the QUIC protocol, but it sounds plausible -- I'd be open to an experiment/PR!

**Comment by lxhao61** [comment]
> tcp proxy
> 
> ```
> {
>    "apps": {
>       "layer4": {
>          "servers": {
>             "srv0": {
>                "listen": [":443"],
>                "routes": [{
>                   "match": [{
>                      "tls": {
>                      }
>                   }],
>                   "handle": [{
>                      "handler": "proxy",
>                      "upstreams": [{
>                         "dial": ["{l4.tls.server_name}:443"]
>                      }]
>                   }]
>                }]
>             },
>             "srv1": {
>                "listen": [":80"],
>                "routes": [{
>                   "match": [{
>                      "http": []
>                   }],
>                   "handle": [{
>                      "handler": "proxy",
>                      "upstreams": [{
>                         "dial": ["{l4.http.host}:80"]
>                      }]
>                   }]
>                }]
>             }
>          }
>       }
>    },
>    "logging": {
>       "logs": {
>          "default": {
>             "encoder": {
>                "format": "json",
>                "time_format": "wall",
>                "time_local": true
>             },
>             "exclude": [],
>             "writer": {
>                "filename": "proxy.event.log",
>                "output": "file",
>                "roll": false
>             }
>          }
>       }
>    }
> }
> ```
> 
> How to proxy quic by sni? udp proxy not work:
> 
> ```
>  "srv11": {
>      "listen": ["udp/:443"],
>      "routes": [{
>         "match": [{
>            "tls": {
>            }
>         }],
>         "handle": [{
>            "handler": "proxy",
>            "upstreams": [{
>               "dial": ["{l4.tls.server_name}:443"]
>            }]
>         }]
>      }]
>   },
> ```

This [PR](https://github.com/mholt/caddy-l4/pull/141.) can achieve your needs, but it is not merged.

**Comment by mholt** [comment]
The linked PR has been merged. Please try it out! (It may not have been 100% complete but should work.)
