### ISSUE TITLE
Cannot create TLS connection over layer 4 connection between Apache/PHP & MariaDB. 

### ISSUE THREAD

**Issue by TheEliteOneShot** [mholt/caddy-l4#17]
I am currently using caddy-l4 as a proxy between my apache web server and MariaDB. My problem is that the connection isn't enforcing a TLS connection and I have tried everything I can think of to get it to work. This is my caddy-l4 configuration for my Maria DB database / Apache server:

```
		"srv1": {
				"listen": ["tcp/caddy:50000"],
				"routes": [
					{
						"handle": [
							{
								"handler": "proxy",
								"upstreams": [
									{"dial": ["tcp/database:3306"]}
								]
							}
						]	
					}
				]
			}
```

This is where I am loading the certifications:

```
	  "tls": {
		"certificates": {
		  "load_files": [
			{
			  "certificate": "/certs/localhost-cert.pem",
			  "key": "/certs/localhost-key.pem",
			  "tags": [
				"cert0"
			  ]
			}
		  ]
		}
	  }
```

And this is where I am routing HTTP traffic through caddy-l4, which is enforcing the TLS connection correctly. When I access the website via localhost I see the lock indicating that the certificate is valid. I am terminating the TLS connection and proxying the connection to webserver:80. The 'alpn' connection_policy was necessary for this to work correctly:

```
		"srv0": {
				"listen": ["0.0.0.0:443"],
				"routes": [
					{
						"handle": [
							{
								"handler": "tls",
								"connection_policies": [
									{"alpn": ["http/1.1"]}
								]
							},
							{
								"handler": "proxy",
								"upstreams": [
									{"dial": ["webserver:80"]}
								]
							}
						]	
					}
				]
			}
```

As you can see, the 0.0.0.0:443 route is enforcing TLS correctly because the traffic is HTTP. However, caddy:50000 is proxying the information correctly but without the TLS connection. The reason I believe this is because when I use the TLS termination or the TLS match handlers, the connection just hangs and doesn't work.

What else can I try here to continue troubleshooting this problem?  Thank you.

**Comment by mholt** [comment]
Might be the same as #18 -- with more discussion there. Fix is in the works; will close this to focus the discussion in the other thread, but feel free to comment if I'm wrong.
