### ISSUE TITLE
Qn: Socks5 TCP Proxy with header and TLS

### ISSUE THREAD

**Issue by marty9x9** [mholt/caddy-l4#170]
This looks amazing. I'm still new to Caddy. Is it possible to do the following?

App unsecure (like JDBC driver) -> caddyl4 Socks5 TCP -> custom PPV2 header before upgrade to TLS -> Secure endpoint

**Comment by mholt** [comment]
Hmm, I think only SOCKS 5 termination is implemented currently, but it should be quite doable to implement a SOCKS 5 client.

**Comment by marty9x9** [comment]
What about sending custom PPV2 header before TLS negotiation?

**Comment by mholt** [comment]
I don't know what PPV2 is.

**Comment by francislavoie** [comment]
I think you mean PROXY Protocol v2? Then yes `layer4.handlers.proxy` supports sending PROXY Protocol bytes ahead of the connection.
