### ISSUE TITLE
Can't build the docker image

### ISSUE THREAD

**Issue by NayanTheSpaceGuy** [mholt/caddy-l4#189]
**Steps to reproduce:**
```
sudo xcaddy build --with github.com/mholt/caddy-l4
```
**Expected Behaviour:**
Build the docker image.

**Current Behaviour:**
Fails to build.

**Host Info:**
Debian 12 (Bookworm) server
xcaddy 0.4.0
golang 1.19.8

**Error Message:**
2024/05/06 21:29:37 [INFO] absolute output file path: /mnt/containers/caddy/caddy_image/caddy
2024/05/06 21:29:37 [INFO] Temporary folder: /tmp/buildenv_2024-05-06-2129.809781120
2024/05/06 21:29:37 [INFO] Writing main module: /tmp/buildenv_2024-05-06-2129.809781120/main.go
package main

import (
        caddycmd "github.com/caddyserver/caddy/v2/cmd"

        // plug in Caddy modules here
        _ "github.com/caddyserver/caddy/v2/modules/standard"
        _ "github.com/mholt/caddy-l4"
)

func main() {
        caddycmd.Main()
}
2024/05/06 21:29:37 [INFO] Initializing Go module
2024/05/06 21:29:37 [INFO] exec (timeout=0s): /usr/bin/go mod init caddy
go: creating new go.mod: module caddy
go: to add module requirements and sums:
        go mod tidy
2024/05/06 21:29:37 [INFO] Pinning versions
2024/05/06 21:29:37 [INFO] exec (timeout=0s): /usr/bin/go get -d -v -tags nobadger github.com/caddyserver/caddy/v2
go: added github.com/beorn7/perks v1.0.1
go: added github.com/caddyserver/caddy/v2 v2.7.6
go: added github.com/caddyserver/certmagic v0.20.0
go: added github.com/cespare/xxhash/v2 v2.2.0
go: added github.com/go-task/slim-sprig v0.0.0-20230315185526-52ccab3ef572
go: added github.com/golang/protobuf v1.5.3
go: added github.com/google/pprof v0.0.0-20210720184732-4bb14d4b1be1
go: added github.com/google/uuid v1.3.1
go: added github.com/klauspost/cpuid/v2 v2.2.5
go: added github.com/libdns/libdns v0.2.1
go: added github.com/matttproud/golang_protobuf_extensions v1.0.4
go: added github.com/mholt/acmez v1.2.0
go: added github.com/miekg/dns v1.1.55
go: added github.com/onsi/ginkgo/v2 v2.9.5
go: added github.com/prometheus/client_golang v1.15.1
go: added github.com/prometheus/client_model v0.4.0
go: added github.com/prometheus/common v0.42.0
go: added github.com/prometheus/procfs v0.9.0
go: added github.com/quic-go/qpack v0.4.0
go: added github.com/quic-go/qtls-go1-20 v0.4.1
go: added github.com/quic-go/quic-go v0.40.0
go: added github.com/zeebo/blake3 v0.2.3
go: added go.uber.org/mock v0.3.0
go: added go.uber.org/multierr v1.11.0
go: added go.uber.org/zap v1.25.0
go: added golang.org/x/crypto v0.14.0
go: added golang.org/x/exp v0.0.0-20230310171629-522b1b587ee0
go: added golang.org/x/mod v0.11.0
go: added golang.org/x/net v0.17.0
go: added golang.org/x/sys v0.14.0
go: added golang.org/x/term v0.13.0
go: added golang.org/x/text v0.13.0
go: added golang.org/x/tools v0.10.0
go: added google.golang.org/protobuf v1.31.0
2024/05/06 21:29:42 [INFO] exec (timeout=0s): /usr/bin/go get -d -v -tags nobadger github.com/mholt/caddy-l4 github.com/caddyserver/caddy/v2
github.com/mholt/caddy-l4 imports
        github.com/mholt/caddy-l4/modules/l4tls imports
        github.com/caddyserver/caddy/v2/modules/caddytls imports
        github.com/smallstep/certificates/authority/provisioner imports
        github.com/slackhq/nebula/cert imports
        `crypto/ecdh: package crypto/ecdh is not in GOROOT (/usr/lib/go-1.19/src/crypto/ecdh)
2024/05/06 21:29:51 [FATAL] exit status 1`

**Comment by mohammed90** [comment]
> golang 1.19.8

Go 1.19 isn't supported. Please use newer Go, preferably latest (1.22).
