### ISSUE TITLE
PR#141 Broke Matchers

### ISSUE THREAD

**Issue by sieveLau** [mholt/caddy-l4#198]
Up to commit 83ccc7e41658de7d5fc02387ed2c91e467e97d94, there is no error with the following config. The two following it make caddy complain:

```text
Error: loading layer4 app module: provision layer4: server 'majorHTTPS': route 0: loading matcher modules: module name 'tls': unknown module: layer4.matchers.tls
```

Here is an example config that you can try:

```json
{
    "apps": {
        "layer4": {
            "servers": {
                "majorHTTPS": {
                    "listen": [
                        "0.0.0.0:443"
                    ],
                    "routes": [
                        {
                            "match": [
                                {
                                    "tls": {}
                                }
                            ],
                            "handle": [
                                {
                                    "handler": "proxy",
                                    "proxy_protocol": "v1",
                                    "upstreams": [
                                        {
                                            "dial": [
                                                "127.0.0.1:8443"
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            }
        }
    }
}
```

I've tested three version (using `caddy build-info | grep caddy-l4`):
1. github.com/mholt/caddy-l4	v0.0.0-20240525154952-83ccc7e41658
2. github.com/mholt/caddy-l4	v0.0.0-20240529173505-6a8be7c4b8ac
3. github.com/mholt/caddy-l4	v0.0.0-20240604210608-ce9789f602eb

Only the first one works. I've tried to read the commits, but I couldn't figure out why the changes breaks the matchers, which seem won't.

**Comment by sieveLau** [comment]
Sorry, I typed the wrong link of the module

**Comment by mholt** [comment]
So just to double-check, nothing for us to fix?

**Comment by sieveLau** [comment]
Yes, everything is fine. I'm sorry that I mistakenly typed `--with github.com/mholt/caddy-l4/layer4` and built some broken executables. After correcting the link to `--with github.com/mholt/caddy-l4`, there is no error.

**Comment by mholt** [comment]
Ah no worries :sweat_smile: Yeah I guess that would do it. Thanks for the clarification!
