### ISSUE TITLE
Nested matching and handling

### ISSUE THREAD

**Issue by contrun** [mholt/caddy-l4#20]
It is a common case that the client sends the HTTP traffic in a TLS session and the proxy forwards it upstream in PROXY protocol. I want to match PROXY protocol and then match TLS session, if the match fails then we should fallback to next route. To the best of my knowledge, there is currently no way to achieve such effect. I propose we implement a special handler called `nested` to handle such case. 

Below is an example configuration. Assume that we have already implemented a matcher called `proxyprotocol` which matches all traffic in PROXY protocol and a handler called `proxyprotocol` which turns PROXY protocol traffic into normal TCP traffic. The below configuration instructs `caddly-l4` to first matches proxy protocol, then unwraps PROXY protocol traffice and handles the unwrapped traffic with the specified routes, which in turn try to match it with tls and then terminate tls, if that fails, match it with the http matcher.

If the entire nested matcher failed to match the connection, we should fallback to the next route. My configuration below makes `caddy-l4` accept both traffic in PROXY protocol and in normal TCP connection.
```
{
  "apps": {
    "layer4": {
      "servers": {
        "example": {
          "listen": ["0.0.0.0:5000"],
          "routes": [
            {
              "match": [
                {
                  "proxyprotocol": {}
                }
              ],
              "handle": [
                {
                  "handler": "proxyprotocol"
                },
                {
                  "handler": "nested",
                  "routes": [
                    {
                      "match": [
                        {
                          "tls": {}
                        }
                      ],
                      "handle": [
                        {
                          "handler": "tls"
                        },
                        {
                          "handler": "proxy",
                          "upstreams": [{ "dial": ["localhost:8080"] }]
                        }
                      ]
                    },
                    {
                      "match": [
                        {
                          "http": [{ "host": ["example.com"] }]
                        }
                      ],
                      "handle": [
                        {
                          "handler": "proxy",
                          "upstreams": [{ "dial": ["localhost:8080"] }]
                        }
                      ]
                    }
                  ]
                }
              ]
            },
            {
              "match": [
                {
                  "tls": {}
                }
              ],
              "handle": [
                {
                  "handler": "tls"
                },
                {
                  "handler": "proxy",
                  "upstreams": [{ "dial": ["localhost:8080"] }]
                }
              ]
            },
            {
              "match": [
                {
                  "http": [{ "host": ["example.com"] }]
                }
              ],
              "handle": [
                {
                  "handler": "proxy",
                  "upstreams": [{ "dial": ["localhost:8080"] }]
                }
              ]
            }
          ]
        }
      }
    }
  }
}
```

**Comment by francislavoie** [comment]
I think you're looking for `subroute`? Or is that not implemented for l4 yet? If not then that should probably be its name to be consistent with Caddy's HTTP app.

**Comment by contrun** [comment]
Yeah. That's what I want. I don't think it is implemented in l4.

**Comment by mholt** [comment]
Ah, yeah, I didn't implement subrouting in this app yet. Would be pretty analogous to the http app's subroute handler: https://github.com/caddyserver/caddy/blob/master/modules/caddyhttp/subroute.go

**Comment by MadhuvanthG** [comment]
@mholt I'm interested in working on this issue. This is my first issue in any module related to Caddy, am someone who's interested in knowing the implementation details of a proxy solution, hence the interest to contribute.

I did play around a bit generally with Caddy to understand the terminologies, architecture etc.. Also, spent some time reading this L4 app codebase. With that, I think, I understand the ask here, but have a few questions-

- there seems to be two parts to the ask here; one is implementing a matcher that can match against PROXY protocol header and another is the ability to do subroutes with handlers. 

- does #27  cover the first ask of matching against incoming PROXY protocol header? 

- I understand that, both these features can be implemented independently, but do you have a preference on which one should be implemented first? I'm open to pick either of them.

Also, please feel free to correct my understanding where necessary.

**Comment by mholt** [comment]
> there seems to be two parts to the ask here; one is implementing a matcher that can match against PROXY protocol header and another is the ability to do subroutes with handlers.

I think that is correct. They are very different things to implement, as you say. Should definitely be two separate PRs.

> does Proxy Protocol Support #27 cover the first ask of matching against incoming PROXY protocol header?

I don't think so.

> I understand that, both these features can be implemented independently, but do you have a preference on which one should be implemented first? I'm open to pick either of them.

The matcher is certainly easier. Probably would be a good place to start.

Thanks for your interest! Looking forward to some reviews. :)

**Comment by MadhuvanthG** [comment]
Opened a PR (^^) for the matcher, could you review please @mholt ?

Also, if you could point me in the right direction for the below, that would be great.

- not sure yet on how to build caddy locally that includes changes to a module. This instruction in [README](https://github.com/mholt/caddy-l4#compiling) doesn't work me, I don't see the layer4 modules, if I build that way.
> In the project folder, run xcaddy just like you would run caddy. For example: xcaddy list-modules --versions (you should see the layer4 modules).

- Not familiar with how could we test this module which operates at layer4? Do we use certain tools to simulate traffic? Although this matcher is very simple, would like to test that it works, to be sure.

**Comment by mholt** [comment]
@MadhuvanthG 

> not sure yet on how to build caddy locally that includes changes to a module. This instruction in README doesn't work me, I don't see the layer4 modules, if I build that way.

Those instructions build with my (mainline) caddy-l4, not your fork. For developing plugins, follow the instructions on the xcaddy README: https://github.com/caddyserver/xcaddy#for-plugin-development

> Not familiar with how could we test this module which operates at layer4? Do we use certain tools to simulate traffic? Although this matcher is very simple, would like to test that it works, to be sure.

I often use `telnet` or `netcat` (`nc`). But yeah you could also programmatically test it.

**Comment by MadhuvanthG** [comment]
Thank you @mholt for the help, I was able to build and test the changes :) Have addressed other comments in the PR as well, please review when you get time.
