### ISSUE TITLE
Log remote addrs for layer4 servers

### ISSUE THREAD

**Issue by melink14** [mholt/caddy-l4#22]
I'm currently trying out caddy-l4 for SSL passthrough to backend service and trying to debug remote address problems throughout the stack.

In this process, I noticed that even with top level logging config set to DEBUG my logs I see logs from my routes but they don't contain any information about the remote client which would be useful for ascertaining what IP caddy thinks is hitting me and implementing remote IP based routing.

```
logging:
  logs:
    default:
      level: "DEBUG"
```

**Comment by mholt** [comment]
Are you referring to these log emissions specifically, which occur at the end of every connection?

https://github.com/mholt/caddy-l4/blob/ddf050b16ae0a735ccf148ebe2101f0d33d17cfb/layer4/server.go#L103-L106

If so, it will be pretty easy to add the client's IP address.

**Comment by melink14** [comment]
That would be a great step for debugging alone but I was also looking for it on the layer4 specific lines like:

`layer4.matchers.tls     matched...`

**Comment by mholt** [comment]
I don't understand. "matched ..." then what? Please be clear about what you're requesting.

**Comment by melink14** [comment]
Ah, I was trying to be clear of course, but there's no way to know if one suceeded until the other party consumes the message. In this case, it seems I failed, so I'll try again.

Logging in caddy-l4 is split up by module. The generic connection stats you mention come from the top level `layer4` logger but there also module specific loggers like `layer4.matchers.tls` or `layer4.handlers.proxy`.

For example here's one log output:
`{"level":"debug","ts":1622757064.589788,"logger":"layer4.handlers.proxy","msg":"dial upstream","address":"localhost:4433"}`

The idea then is to be able to add a connecting IP field to these module specific log lines since it's a key property of each step of the processing.

That being said, the top level connection stats contain IP goes a long way in debugging general problems but wanted to describe the more general idea as well.

**Comment by mholt** [comment]
Ok, gotcha. Thanks. I added the remote IP to a bunch of logs in 3cfcafe.
