### ISSUE TITLE
SIGHUP for config reload?

### ISSUE THREAD

**Issue by stronny** [mholt/caddy-l4#226]
The documentation leaves no options for a reload beyond the admin API, however I run caddy with it completely disabled and rely on autoreload instead. I would prefer to control the reload event somehow, rather than it being unavoidable on every file modification (or no reload at all).

I'm prepared to do some coding, but would appreciate pointers from the team. Is it possible to make it a module or is it hardcoded into caddy sufficiently enough that it's only possible with a PR against the main repo?

**Comment by francislavoie** [comment]
See https://github.com/caddyserver/caddy/issues/3967, signals are fundamentally incompatible with how Caddy config is loaded because signals do not carry any input.

**Comment by mholt** [comment]
SIGHUP is used when the SSH client disconnects from a server. It's not an appropriate signal for config changes. And signals for config changes don't really make sense in Caddy anyways since its config is received via an API endpoint, and signals don't have any data associated with them.

That said, you can probably do anything you want in a plugin of your own. I can't remember off-hand but we might eat SIGHUP intentionally, since sometimes it would quit the server when the client disconnected.

>  I run caddy with it completely disabled and rely on autoreload instead

Just to clarify, that's not possible because the config reload functionality uses the admin API. You can stop and restart the server but without the admin API there's no way to give Caddy config data.

**Comment by stronny** [comment]
Right, let's break this down.

# the signal
By dismissing `HUP` as an appropriate signal, you are effectively throwing away 30 years of systems administration. Here's a quote from Wikipedia:

> Signals have always been a convenient method of inter-process communication (IPC), but in early implementations there were no user-definable signals (such as the later additions of SIGUSR1 and SIGUSR2) that programs could intercept and interpret for their own purposes. For this reason, applications that did not require a controlling terminal, such as daemons, would re-purpose SIGHUP as a signal to re-read configuration files, or reinitialize. This convention survives to this day in packages such as Apache and Sendmail.

https://en.wikipedia.org/wiki/SIGHUP

You can google "config reload on SIGHUP" and discover thousands of examples of quite well-established software that does exactly that. I suppose you can check for a tty if you want to exercise the abundance of caution, but usually peeps don't bother I don't think.

# the signals
If I run caddy telling it to read `/etc/caddy.json` as its config file, what information exactly does a signal need to carry, again? It literally notifies a process to re-read and re-apply its config file, it doesn't need any context to this request.

"But signals don't work on windows!" Luckily I don't run caddy on windows.

# automatic reload
https://caddyserver.com/docs/command-line#caddy-run says:

> `--watch` will watch the config file and automatically reload it after it changes. ⚠️ This feature is intended for use only in local development environments!

And I agree, it's not ideal for a production server, ergo this issue. How do you mean it's impossible? I'm pretty sure it works as advertised, but I will check again later.

**Comment by stronny** [comment]
I'm so sorry, this issue meant to go into caddy, not L4. My bad, if there's a way to transfer it there, please do that.

**Comment by stronny** [comment]
I think I'll just close this and repost into the existing issue.
