### ISSUE TITLE
[Question] [Regression?] Upgrading Caddy from 2.7.6 to 2.8.4 with layer4 rebuild breaks SNI-based routing

### ISSUE THREAD

**Issue by Unb0rn** [mholt/caddy-l4#238]
I've been using Caddy 2.7 with l4 for quite some time. Last  time I rebuilt the image (2.7.6-alpine) was like in May and this configuration worked fine for me.
Now, after rebuilding Caddy 2.8.4 with the actual l4 module, my SNI-filtered TLS traffic won't reach my OpenConnect Server.

What I'm trying to achieve:
I want to "multiplex" 443 port and use it between several services - for now Caddy and ocserv
I set up caddy so it would use port 80 for http, 8443 for https and 443 for layer4, then if SNI matched some domain I would forward it to some upstream service (ocserv, for example) with proxy_protocol and for all other cases (like any other domain) forward the traffic back to Caddy default app (https on port 8443)

After my last upgrade to 2.8.4, https part (all other domains) works fine, but ocserv one doesn't seem to forward traffic to the service anymore and the problem is - I cannot understand what's changed?

The configuration I used:
[caddy-config.json](https://github.com/user-attachments/files/16648064/caddy-config.json)

All I changed in config (to migrate from 2.7 to 2.8 was changing `challenges` to `cname_validation` and removing email for zerossl issuer

Also, can we please enable discussions for topics like this one - I'm not sure if it's a bug or some legitimate change.

**Comment by francislavoie** [comment]
See https://github.com/mholt/caddy-l4/issues/234

**Comment by WeidiDeng** [comment]
It's indeed a regression. I'll fix it tomorrow. Meanwhile, you can add tls matchers to ocserv as a workaround for now.

**Comment by WeidiDeng** [comment]
@Unb0rn Can you try `xcaddy build --with github.com/mholt/caddy-l4=github.com/WeidiDeng/caddy-l4@prefetch-fix`?
