### ISSUE TITLE
Question: Reverse tunneling to caddy behind a NAT

### ISSUE THREAD

**Issue by crabdancing** [mholt/caddy-l4#242]
My setup is as follows:
1. a VPS (ingress point)
2. A tunnel to move incoming connections from my VPS to my (NAT) business network
3. Caddy (as a unified TLS frontend & reverse proxy)
4. local services on my business network

One of the constraints here is that I can't have the TLS encryption happen on the VPS, as that would in principle allow the VPS to spy on unencrypted traffic.

The problem is that every tunnel technology I've tried resets all IP address information about the connection. This is unacceptable, as the backend service can't block bruteforcing attempts or otherwise punish misbehavior based on IP address. 

How do I set up a backend on the server such that clients can connect to the VPS as if the services were hosted there, and have them actually connect to a service on my business network, while still having a useful X-Forwarded-For / X-Real-IP that the services can use to identify the incoming connection? Can I use caddy-l4 on both VPS & backend?

**Comment by mohammed90** [comment]
You need to use the [PROXY Protocol](https://seriousben.com/posts/2020-02-exploring-the-proxy-protocol/). Both, the HTTP server in standard Caddy and this module support the PROXY protocol. If you just need HTTP, then use the `proxy_protocol` [listener_wrapper](https://caddyserver.com/docs/caddyfile/options#listener-wrappers) in the HTTP app. Otherwise, you can enable the use of the [`proxy_protocol` option](https://caddyserver.com/docs/modules/layer4.handlers.proxy#proxy_protocol) in the [`proxy` handler](https://caddyserver.com/docs/modules/layer4.handlers.proxy) of the layer4 app.

**Comment by crabdancing** [comment]
I think what I want to do is:

![image](https://github.com/user-attachments/assets/bd8caf35-2eef-435b-9154-91c473e6e801)

Is this correct? Sorry, I'm kind of new to Caddy.

I've been trying to figure out the `listener_wrapper` thing for awhile, but I can't really find any good examples.

**Comment by mohammed90** [comment]
You're very close. You don't need 2 Caddy instances on the trusted server. The Caddy with layer4 will listen on port 443 and only proxies to the other Caddy instance using the `proxy_protocol`. The backend Caddy instance needs to have `proxy_protocol` in its `listener_wrappers` part of the config. The `listener_wrappers` manipulate the connection data before being processed by the HTTP app of Caddy. In this case, using the `proxy_protocol` listener wrapper removes the bits added by the Proxy Protocol to the HTTPS request, turning them back into regular HTTPS request.

Your config _may_ end up being something like this --

- caddy-l4 config:

```caddyfile
{
    layer4 {
        0.0.0.0:443 {
            route {
                proxy {
                    proxy_protocol v2
                    upstream 192.168.1.200:443
                }
            }
        }
    }
}
```

- Backend Caddy:

```caddyfile
{
	servers {
		listener_wrappers {
			proxy_protocol {
				allow 192.168.86.1/24 # replace this with the IP address of the server of caddy-layer4
				fallback_policy
			}
			tls
		}
	}
}
example.com {
	reverse_proxy backend-1:80 backend-2:80
}
```

**Comment by crabdancing** [comment]
@mohammed90 Oh, thanks so much. :) I really appreciate the help!

I'm starting to understand better, but the one thing that confuses me is the direction of the connection. In this setup, does it require port 443? Am I correct in inferring that `192.168.1.200` is the IP of the backend in this example?

If that's the case, does that mean that the caddy-l4 VPS server opens the connection to the backend, and not vice versa? If it is behind a NAT, it may or may not be feasible to port forward, so I was hoping to have the connection come from behind the NAT.

**Comment by mohammed90** [comment]
> In this setup, does it require port 443?

The layer4 instance, yes, because this is what the public ACME servers require to validate the certificate requests. For the inner Caddy, you can tell Caddy to expect HTTPS on a different port by using the [`https_port` global option](https://caddyserver.com/docs/caddyfile/options#https-port).

> Am I correct in inferring that `192.168.1.200` is the IP of the backend in this example?

Yes.

> If that's the case, does that mean that the caddy-l4 VPS server opens the connection to the backend, and not vice versa?

Correct

> If it is behind a NAT, it may or may not be feasible to port forward, so I was hoping to have the connection come from behind the NAT.

This is not something Caddy can help you with. You can run an SSH reverse-tunnel or VPN between the nodes.

**Comment by crabdancing** [comment]
Oof. I was using SSH, but I think FRP might be more performant, so I'll try setting that up. Thank you for all your help. :)

**Comment by crabdancing** [comment]
@mohammed90 

I've got the HTTPS connection to go from VPS to remote server over caddy+L4 -> FRPS -> FRPC. And now it shows binary data (presumably PROXY-wrapped HTTPS) when I `nc -l 4443` from the backend, and `curl https://$VPS_IP` from another terminal.

There is one more issue. How do I make the backend side listen for proxy connections (e.g., port 4443, or whatever else)? If I grep `netstat -ltpn` for `caddy`, I get:

```
tcp        0      0 127.0.0.1:2019          0.0.0.0:*               LISTEN      1418094/caddy
tcp6       0      0 :::443                  :::*                    LISTEN      1418094/caddy
tcp6       0      0 :::80                   :::*                    LISTEN      1418094/caddy
```

With the following config, inspired by your example:

```caddyfile
{
	servers {
		listener_wrappers {
			proxy_protocol {
				allow 127.0.0.1/24
			}
			tls
		}
	}
}
```

**Comment by crabdancing** [comment]
Oh, fair enough. That was silly of me. I think I was confused because you have to specify something ilke 'allowed/trusted proxies' in multiple places, so it was easier to overlook that line when sleepy. I imagine this is because of the modulerized structure of caddy's internals -- caddy-l4 has its own source IP permissions separate from the whole of the application.

> Also, you might want to check Authelia's docs for trusting X-Forwarded-* headers: https://www.authelia.com/integration/proxies/forwarded-headers/

No worries, I already understand the security implications of proxy headers, so I'm good on that front. :) Thank you for the warning about `fallback_policy`. I will be sure to add that back.

Thank you for your help. It works as it should now.
