### ISSUE TITLE
Support  tls for postgres 17

### ISSUE THREAD

**Issue by divyam234** [mholt/caddy-l4#256]
Postgres 17 has introduced direct ssl [negotiation](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNECT-SSLNEGOTIATION) so using tls with sni should work without any changes. Currently getting this error below

```
"level":"error","ts":1729340050.662618,"logger":"caddy.listeners.layer4","msg":"handling connection","error":"tls: client requested unsupported application protocols ([postgresql])"}
```
What changes are needed to support new changes from postgres?

**Comment by mholt** [comment]
Did you mean to close this? Was your question answered?

**Comment by divyam234** [comment]
Yeah in https://github.com/mholt/caddy-l4/issues/243#issuecomment-2424115348
