### ISSUE TITLE
SSH Proxy - Question

### ISSUE THREAD

**Issue by gt2416** [mholt/caddy-l4#26]
Sorry if this is a noob question.
This plugin will allow me to proxy ssh to a local ip? For example ssh.myserver to localhost:22? 
The reason I want this is that I’m behind a corporate firewall that blocks outgoing ssh connections. 
However if I could cloak it in https traffic it would work. As long I configure sshd to respond to http requests then this plugin should is what I’m looking for correct ? I believe you can do this with apache using http connect module.

**Comment by francislavoie** [comment]
> However if I could cloak it in https traffic it would work.

It would still be raw TCP traffic. This plugin wouldn't "cloak" anything as HTTPS. All this does is raw TCP/UDP connections and traffic, then allows you to handle it depending on the shape of the data.

**Comment by mholt** [comment]
This module can be used to "cloak" connections but clients have to be configured to work with it. For example, TLS-in-TLS. You could in theory do SSH-in-TLS too, but you'd need a wacky SSH client that can establish a TLS handshake and then send SSH over it. :man_shrugging:

**Comment by gt2416** [comment]
Thanks, I’ll test and see if it works.  If your curious this is the setup I want to replicate 
https://nurdletech.com/linux-notes/ssh/via-http.html

It’s just I use caddy as my front reverse proxy and am happy with it. Don’t want to switch to Apache. Anyway I think this may work or at the very least allow me to have ssh.myserver dns which listens on 443 rather than port 22 which might allow me to bypass the firewall.

**Comment by mholt** [comment]
So if I understand correctly, you want to serve both HTTP(S) and SSH on the same port (either 80 or 443)?

If so, you don't need any special client. Just use the `ssh` matcher to proxy SSH connections to your SSH server, and everything else to your HTTP server. (Similar examples are in our README.)

Will close now as I think that should answer your question...
