### ISSUE TITLE
Is it possible to match tcp requests based on host for SSH connections.

### ISSUE THREAD

**Issue by ShadowFox88** [mholt/caddy-l4#265]
So I have a server running Caddy, which has everything reverse proxied. Is it possible for me to route tcp requests based on the host ie ssh1.example.com will go to localhost:23 and ssh2.example.com will go to localhost:24, where both ssh1 and ssh2 run on port 22 and depending on the host provided, it'll choose where to send it?

I've tried something along the lines of 
```
{
        layer4 {
                :22 {
                        @ssh1 sni ssh1.example.com
                        route @ssh1 {
                                proxy {
                                        upstream localhost:23
                                }
                        }

						@ssh2 sni ssh2.example.com
						route @ssh2 {
								proxy {
										upstream localhost:24
								}
						}

                }
		}
}
``` 
but that didn't seem to work for me.

Simply switching to
```
{
        layer4 {
                :22 {
                        @ssh1 sni ssh1.example.com
                        route @ssh1 {
                                proxy {
                                        upstream localhost:23
                                }
                        }
				}
		}
}
```
 doesn't pass my requests to localhost:23 either.

**Comment by mholt** [comment]
SSH doesn't use Server Name Indication (SNI). That's a TLS thing. I don't think SSH has any similar concept.

**Comment by ShadowFox88** [comment]
Ah, thanks for the help! I found that solution to not fit my use case, so I opted for [this](https://github.com/tg123/sshpiper) to allow me to configure ssh routing through usernames!

**Comment by mholt** [comment]
You can do that? Huh.

@vnxme Did you know that? :smile:

**Comment by ShadowFox88** [comment]
> You can do that? Huh.
> 
> @vnxme Did you know that? :smile: 

It's a bit of a hacky solution because it performs a MITM attack on yourself, and thus has the added overhead of setting up a key twice, but otherwise it works great

**Comment by mholt** [comment]
Ah, I see. That makes sense I guess :thinking:

**Comment by vnxme** [comment]
@ShadowFox88 Thanks for the link. I didn’t know such a solution exists in a relatively small go app. I’ve seen an enterprise-level project doing something like that and more, but can’t recall its name now.
