### ISSUE TITLE
How do I proxy a smtp server?

### ISSUE THREAD

**Issue by nitanmarcel** [mholt/caddy-l4#270]
I'm using [hydroxide](https://github.com/emersion/hydroxide) to use protonmail with smtp and I can't seem to make it work. Maybe I understood wrong how to use this module

My layer4 config is this:

```
	layer4 {
		0.0.0.0:993 {
			@secure tls
			route @secure {
				proxy localhost:1025 # hydroxide address
			}
		}
	}
```

But when I try to send an email with smtp it fails to work

```
Nov 19 15:11:21 ubuntu caddy[369383]: {"level":"debug","ts":1732029081.9104574,"logger":"layer4","msg":"matching","remote":"54.212.131.181:54809","error":"consumed all prefetched bytes","matcher":"layer4.matchers.tls","matched":false}
Nov 19 15:11:24 ubuntu caddy[369383]: {"level":"warn","ts":1732029084.9107566,"logger":"layer4","msg":"matching connection","remote":"54.212.131.181:54809","error":"aborted matching according to timeout"}
Nov 19 15:11:24 ubuntu caddy[369383]: {"level":"debug","ts":1732029084.910865,"logger":"layer4","msg":"connection stats","remote":"54.212.131.181:54809","read":0,"written":0,"duration":3.000585675}
```

**Comment by vnxme** [comment]
If you want to handle anything inside TLS, you have to put the `tls` handler before the `proxy` handler:
```
	layer4 {
		0.0.0.0:993 {
			@secure tls
			route @secure {
				tls
				proxy localhost:1025 # hydroxide address
			}
		}
	}
```
But I don't use SMTP over TLS in Caddy or hydroxide, so I can't check whether it works or not.

**Comment by mohammed90** [comment]
My understanding is that STARTTLS of SMTP isn't a simple SMTP wrapped by TLS. It follows a specific state machine within SMTP protocol to initiate the TLS connection. In other words, the server/client has to be STARTTLS/SMTP aware.

**Comment by nitanmarcel** [comment]
> If you want to handle anything inside TLS, you have to put the `tls` handler before the `proxy` handler:
> 
> ```
> 	layer4 {
> 		0.0.0.0:993 {
> 			@secure tls
> 			route @secure {
> 				tls
> 				proxy localhost:1025 # hydroxide address
> 			}
> 		}
> 	}
> ```
> 
> But I don't use SMTP over TLS in Caddy or hydroxide, so I can't check whether it works or not.

This for some reason hanged any requests made to the port. Anyway, I've managed to host a smtp server for my needs :)

And about the layer4 config, [docker-mailserver](https://github.com/docker-mailserver/docker-mailserver) seems to take care of tls, and startssl, with a little help from caddy's auto generated ssl certificates.

So my candy files looks like this:

```
{
	layer4 {
		0.0.0.0:587 {
			route {
				proxy localhost:1587
			}
		}
		0.0.0.0:993 {
			route {
				proxy localhost:1993
			}
		}
	}

}

mail.example.com {
  tls internal {
    key_type rsa2048
  }

  # Optional, can be useful for troubleshooting
  # connection to Caddy with correct certificate:
  respond "Hello DMS"
}
```

And the certificates are mounted in docker:

```
      - /var/lib/caddy/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/mail.example.com/mail.example.com.crt:/etc/letsencrypt/live/mail.example.com/fullchain.pem
      - /var/lib/caddy/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/mail.example.com/mail.example.com.key:/etc/letsencrypt/live/mail.example.com/privkey.pem
```

**Comment by nitanmarcel** [comment]
For what matters, `@secure tls` will block the traffic, unless the client is told to use tls instead of startls
