### ISSUE TITLE
Configuration Help

### ISSUE THREAD

**Issue by gt2416** [mholt/caddy-l4#32]
Hi, I really don't understand how to use json format so please bear with me for this simple question.
I want to route ssh to say 192.168.0.11:22, from ssh.mydomain.com.
I added  this at the end of my json after the cloudlfare dns stuff. It doesnt seem to work, I get a` kex_exchange_identification: Connection closed by remote host` error.

````
}, # end of cloudflare plugin block
		"layer4": {
			"servers": {
				"srv0": {
					"listen": [
						":443"
					],
					"routes": [
						{
							"match": [
								{
									"ssh": {}
								}
							],
							"handle": [
								{
									"handler": "proxy",
									"upstreams": [
										{
											"dial": [
												"192.168.0.11:22"
											]
										}
									]
								}
							]
						}
					]
				}
			}
		}
	}
````

Any help would be greatly appreciated. Thanks

**Comment by gt2416** [comment]
NVM, I figured it out, You can close this !

**Comment by ThisIsTenou** [comment]
> NVM, I figured it out, You can close this !

Might sharing the solution with us in case others stumble upon the same issue?

**Comment by gt2416** [comment]
Sure, I had to add another matcher so that it knows what subdomain to listen for.  
So the config ended up being 
````
"layer4": {
			"servers": {
				"srv0": {
					"listen": [
						":443"
					],
					"routes": [
						{
							"match": [
								{
									"host": [
										"ssh.mydomain.com"
									]
								}
							],
							"match": [
								{
									"ssh": {}
								}
							],
							"handle": [
								{
									"handler": "proxy",
									"upstreams": [
										{
											"dial": [
												"192.168.0.11:22"
											]
										}
									]
								}
							]
						}
					]
				}
			}
		}
````

**Comment by mholt** [comment]
@gt2416 Hmm, that's odd. There is no `host` matcher in layer4, without the `http` matcher first. And you have two `match` keys where one is overriding the other (second is kept).

I suspect you did something else different to make it work.

**Comment by gt2416** [comment]
If I remove that matcher it stops working, however I know it is not matching anything. Its just that the ssh.mydomain.com isnt there anywhere else in the file. 
If I try adding a second block with ssh2.mydomain.com to proxy to ip2, it lets me ssh but goes to proxy ip1 (the one defined for ssh.mydomain.com) so yea Im def doing something weird. 
Like I said I don't know how to use json, what I do is write my caddy file, copy the json from the autosave location and add this layer4 code block at the end. My json file is 650lines, I dont plan to learn to use completely lol, caddyfile is a lot easier.
How would I go about doing this, ssh.mydomain.com -- IP1, ssh2.mydomain.com --IP2  ?

**Comment by mholt** [comment]
> If I remove that matcher it stops working, however I know it is not matching anything. Its just that the ssh.mydomain.com isnt there anywhere else in the file.

Sure, but that shouldn't affect SSH, which doesn't use HTTP or TLS.

> Like I said I don't know how to use json, what I do is write my caddy file, copy the json from the autosave location and add this layer4 code block at the end. 

Instead of using autosave, use the `caddy adapt` command.

> ssh.mydomain.com -- IP1, ssh2.mydomain.com --IP2 ?

I'm not sure what you mean. SSH doesn't distinguish hostnames like HTTP does.
