### ISSUE TITLE
Is this tool stable enough in the production environment?

### ISSUE THREAD

**Issue by hongyi-zhao** [mholt/caddy-l4#34]
I learned about this project from the comment [here](https://caddy.community/t/fowarding-to-target-website-via-a-socks5-proxy/12349/2?u=hongyi-zhao), and it seems that it's similar to but more powerful than the nginx's stream module. But I'm not sure whether this project is stable enough for the product use scenario. Any hints will be highly appreciated.

Regards,
HZ

**Comment by mholt** [comment]
Should be, yes. Depends what your specific requirements are, but it seems to be _stable_ in terms of working.

**Comment by hongyi-zhao** [comment]
Thank you for the comment. I'll try to test it out. Say, I want to implement the following network workflow with caddy-l4:

`$ socat -v -d -d TCP4-LISTEN:9999,fork,reuseaddr socks5:127.0.0.1:10.8.10.220:2021,socks5port=6001`

What configuration file should I use with caddy-l4?

**Comment by mholt** [comment]
I'm not familiar with `socat`. I could read the man page, but I can help you much faster if you explain to me what that command is doing. Listening on port 9999, and creating a SOCKS5 tunnel from port 6001 to 10.8.10.220:2021, something like that?

**Comment by hongyi-zhao** [comment]
Sorry for later reply. I feel a little sick during this period and can’t watch the computer for a long time. 

> I'm not familiar with `socat`. I could read the man page, but I can help you much faster if you explain to me what that command is doing. 

Sorry for my inadequate explanation of my intention and the usage details of the powerful but rather obscure tool [`socat`](https://github.com/runsisi/socat).

> Listening on port 9999, and creating a SOCKS5 tunnel from port 6001 to 10.8.10.220:2021, something like that?

Your understanding is basically correct. For more details, please refer to the following:
```
$ socat -v -d -d TCP4-LISTEN:9999,fork,reuseaddr socks5:127.0.0.1:10.8.10.220:2021,socks5port=6001
-d[ddd]         increase verbosity (use up to 4 times; 2 are recommended)
-v     verbose data traffic, text
```

Listening on the localhost 9999 port of TCP4/IPV4 addresses, and build a bidirectional socket/tunnel to the remote http server running on `http://10.8.10.220:2021`, which can be accessed via the locally socks5 server listening on 127.0.0.1:6001.

Finally,  on localhost, when I open `http://127.0.0.1:9999` in browser, say, Firefox, the http://10.8.10.220:2021 will be opened.

Regards,
HZ

**Comment by mholt** [comment]
Ok. So yeah, you can proxy TCP traffic with this and it should work fine. It doesn't have any understanding of the SOCKS protocol (yet?) but it does recognize SSH. So you could use that to your advantage if helpful.

(Closing, as hopefully the question is answered.)

**Comment by hongyi-zhao** [comment]
If it doesn't understand the SOCKS protocol, how can it communicate well with the socks5 proxy server for forwarding?

**Comment by mholt** [comment]
Because it proxies TCP packets, it doesn't care what the protocol is. It only needs to understand SOCKS if you want to do something SOCKS-specific.

**Comment by hongyi-zhao** [comment]
If the socks5 proxy server needs authentication, say, username/password type, how to deal with it?

**Comment by francislavoie** [comment]
All packets will be proxied. So if your upstream SOCKS server sends back a request for authentication, caddy-l4 will proxy that back to the client.

**Comment by hongyi-zhao** [comment]
Then, after receiving the authentication request, how to further interoperate with it?

**Comment by francislavoie** [comment]
That's not a question relevant to this project, really. Since `caddy-l4` has no SOCKS support, there's no relevant manipulations it can make to the traffic being sent through. But you can use `caddy-l4` to be a "middle-man" to the data.

**Comment by hongyi-zhao** [comment]
By saying  a "middle-man", do you mean a transparent TCP packets bidirectional forwarding gateway?

**Comment by francislavoie** [comment]
Pretty much, if you want to call it that.

**Comment by mholt** [comment]
If you do need to understand the SOCKS protocol for some reason (for example, to do SOCKS-specific things), that can definitely be implemented.

**Comment by hongyi-zhao** [comment]
> If you do need to understand the SOCKS protocol for some reason (for example, to do SOCKS-specific things), 

Yes. Not only stay at the level of understanding, but I can't live without the help of Socks5 protocol in my daily use. The Socsk5 protocol is a valuable tool for me to access the internet/intranet when, for some reason, I cannot directly access a particular internet/intranet resource in the normal way.

> that can definitely be implemented.

In this specific scenario discussed here, the socks5 proxy server is supplied by an ssh remote port forwarding. But I don’t know what the exact implication of your above point of view. Where is can be implemented? From within caddy-l4 or other places?

**Comment by mholt** [comment]
If all you need to do is proxy SSH, there's an example on the readme for that. If you need to change something about the SOCKS tunnel specifically, then yeah, that kind of functionality could be implemented within caddy-l4. :+1:

**Comment by hongyi-zhao** [comment]
I think it is a good idea to make it a versatile tool that supports all possible scenarios. Today and tomorrow I may have different needs. Others and I may have different needs. We are unlikely to anticipate all possible application scenarios in advance. The only wise way is to enable our tools to deal with all possible important scenarios.
