### ISSUE TITLE
AMQP Connection not possible

### ISSUE THREAD

**Issue by Gr33nbl00d** [mholt/caddy-l4#35]
While connecting through the proxy a connection to a RabbitMQ Server via AMQP Protocol was not possible.
Error Message given is:
com.rabbitmq.client.MalformedFrameException: AMQP protocol version mismatch; we are version 0-9-1, server sent signature 0,0,9,1

It seems like a problem in initial handshake. Version is correct on both sides and connection can be established without problems not using caddy-l4 proxy

**Comment by mholt** [comment]
I'm not familiar with AMQP. What's your config? How can we reproduce this from scratch?

Someone more familiar with AMQP might have to look into it.

**Comment by Gr33nbl00d** [comment]
Hi big sorry i had a little misunderstanding of the docu i guess. 
I used the setting "proxy_protocol" which caused the issue.
I thought that the  proxy_protocol setting is related to the internal protocol of caddys proxy handler ;)
