### ISSUE TITLE
Specify IP addresses for the IP matcher, send all other packets to a sort-of sinkhole port, and set a specific address or subdomain for the ssh matcher

### ISSUE THREAD

**Issue by shadowrylander** [mholt/caddy-l4#37]
Hello!

In a similar vein to this [Configuration Help](https://github.com/mholt/caddy-l4/issues/32) issue by @gt2416, several questions:
* How do I specify IP addresses for the IP matcher? Is it a simply array, such as the HTTP matcher, or a hash table / dictionary, such as the TLS matcher, or something else entirely?
* How can I send all other packets to a sort-of sinkhole port or domain, such as the [anyprot option](https://www.systutorials.com/docs/linux/man/8-sslh/#:~:text=%2D%2Danyprot%20target%20address,first%20protocol%20specified.) of [sslh](https://github.com/yrutschle/sslh)?
* And as in the aforementioned issue, how do I set a specific address or subdomain for the ssh matcher?

Thank you kindly for the help!

**Comment by francislavoie** [comment]
> How do I specify IP addresses for the IP matcher? Is it a simply array, such as the HTTP matcher, or a hash table / dictionary, such as the TLS matcher, or something else entirely?

It's an array of CIDR strings. You can see the structure in the code here: https://github.com/mholt/caddy-l4/blob/31d74d38aa3a41c1563f25dfbee24ced3d4afae2/layer4/matchers.go#L96. Something like this:

```json
	"match": [
		{
			"ip": [
				{"ranges": ["192.168.0.0/16", "172.16.0.0/12", "10.0.0.0/8"]}
			]
		}
	],
```

> How can I send all other packets to a sort-of sinkhole port or domain, such as the anyprot option of sslh?

Hmm, I don't think there's a handler to do that yet, similar to Caddy's [`abort` handler](https://caddyserver.com/docs/caddyfile/directives/abort), but that should be trivial to implement. It might behave about the same if you just leave the request unhandled (like, use matchers to match other valid requests, but don't have a handler for anything else)

> And as in the aforementioned issue, how do I set a specific address or subdomain for the ssh matcher?

Unfortunately, it's not possible to route by subdomain with protocols like SSH, because the subdomain is not sent along in the packets. With HTTP, it's sent in either the `Host` header, or in TLS-SNI (Server Name Identification), but there's no such thing for SSH. So if you want to proxy SSH to multiple hosts, you'll need to use a different port number for each, or have multiple actual network adapters with unique IPs that you can bind/listen to.

**Comment by shadowrylander** [comment]
Also, I should clarify that I'm using [layer4](https://github.com/mholt/caddy-l4) as well; sorry about that! Does that change anything?

**Comment by francislavoie** [comment]
All my comments were with that in mind.

**Comment by shadowrylander** [comment]
... Oops... Forgot... 😅 Anyways...

Could you possibly then expand upon why the method described [here](https://github.com/mholt/caddy-l4/issues/32#issuecomment-960838855) works, though?

**Comment by francislavoie** [comment]
We don't think it actually worked, and the user gave us a config they weren't actually running. Because if we try that same config, `caddy-l4` fails to load, since there's no `host` matcher, as Matt wrote there. I don't think the information in that issue can be trusted.

**Comment by shadowrylander** [comment]
Ah; fair enough. That's unfortunate.

Two more things, if I may:
1. What are the configuration options for the SSH matcher, like IP, HTTP, and TLS?
2. Can you set a root directory for the SSH matcher, or even a `file_server` directive, so I can do something like `git clone user@address:` and clone down a repository? For https, I can set up a `file_server` with a specified root in a repository's `.git` directory, and then clone it with `git clone https://address`.

**Comment by francislavoie** [comment]
> What are the configuration options for the SSH matcher, like IP, HTTP, and TLS?

There's no options. It's either "the TCP request is SSH" or it isn't.

https://github.com/mholt/caddy-l4/blob/31d74d38aa3a41c1563f25dfbee24ced3d4afae2/modules/l4ssh/matcher.go#L30

> Can you set a root directory for the SSH matcher, or even a file_server directive, so I can do something like git clone user@address: and clone down a repository? For https, I can set up a file_server with a specified root in a repository's .git directory, and then clone it with git clone https://address.

No, the matcher is just "is this SSH", by looking at the first few bytes of the connection.

Nothing else for SSH is implemented right now. You could write your own plugin if you need more functionality.

**Comment by shadowrylander** [comment]
I wish I could, but I have no knowledge of Go at the moment, unfortunately. Do you have any recommendations on how I could achieve the ssh git cloning functionality I'm looking for with `caddy l4`?

**Comment by mholt** [comment]
I'm not familar enough with how SSH + git works to know how to write the matcher for that. But I'm sure the existing SSH matcher could be expanded to look for specific uses of SSH somehow.

**Comment by shadowrylander** [comment]
Hmm... Apparently the safest way to set the root for an SSH session would be to create a chroot jail, which is most likely _entirely_ out of the scope of `caddy l4`...

Ah, well; as it were, thank you both kindly for the help! If I have any further questions, I'll create another issue!
