### ISSUE TITLE
l4proxy: Upstream connections may be closed before reading from them

### ISSUE THREAD

**Issue by RussellLuo** [mholt/caddy-l4#40]
## Problem

The close of upstream connections:

https://github.com/mholt/caddy-l4/blob/31d74d38aa3a41c1563f25dfbee24ced3d4afae2/modules/l4proxy/proxy.go#L173-L178

may happen before the reading of replies from the upstream connections:

https://github.com/mholt/caddy-l4/blob/31d74d38aa3a41c1563f25dfbee24ced3d4afae2/modules/l4proxy/proxy.go#L256-L263

As a result, **the replies from upstream servers will never be forwarded to the downstream clients**. 

## Reproducer

Given a slow Echo server:

```go
package main

import (
	"io"
	"log"
	"net"
	"time"
)

type SlowConn struct {
	net.Conn
}

func (c SlowConn) Write(p []byte) (n int, err error) {
	time.Sleep(5 * time.Millisecond) // Write slowly
	n, err = c.Conn.Write(p)
	return
}

func main() {
	ln, err := net.Listen("tcp", ":7070")
	if err != nil {
		log.Panicln(err)
	}
	defer ln.Close()

	for {
		conn, err := ln.Accept()
		if err != nil {
			log.Panicln(err)
		}

		go handle(conn)
	}
}

func handle(conn net.Conn) {
	c := SlowConn{Conn: conn}
	if _, err := io.Copy(c, c); err != nil {
		log.Printf("err: %v\n", err)
	}
	conn.Close()
}
```

Everything is OK:

```bash
$ echo "hi" | nc localhost 7070
hi
```

Run Caddy with the following JSON config:

```json
{                                       
        "apps": {                       
                "layer4": {                     
                        "servers": {                    
                                "srv0": {
                                        "listen": [":8080"],
                                        "routes": [                             
                                                {                       
                                                        "handle": [     
                                                                {
                                                                        "handler": "proxy",
                                                                        "upstreams": [
                                                                                {"dial": ["localhost:7070"]}
                                                                        ]
                                                                }
                                                        ]
                                                }
                                        ]
                                }
                        }
                }
        }
}
```

Nothing will be displayed:

```bash
$ echo "hi" | nc localhost 8080
```

**Comment by RussellLuo** [comment]
May be related to [netcat (nc) doesn’t terminate at end of transmission](http://billauer.co.il/blog/2018/07/netcat-nc-stop-quit-disconnect/).

**Comment by mholt** [comment]
Oohh, good find. Do you want to make PR from your fork? I like the WaitGroup solution much better.

**Comment by RussellLuo** [comment]
## New Problem

Unfortunately, the WaitGroup solution introduces a new problem - `nc` will get blocked until the Echo server is closed:

```
$ echo "hi" | nc localhost 7070
hi
(BLOCKED HERE)
```

The reason is that when the downstream connection is closed (half-closed in the `nc` case), the following `io.Copy` will return:

https://github.com/mholt/caddy-l4/blob/31d74d38aa3a41c1563f25dfbee24ced3d4afae2/modules/l4proxy/proxy.go#L267-L269

but then will immediately get blocked by `wg.Wait()`. In this case, the only thing I can do is to close the Echo server, thus make the `io.Copy` in goroutines return:

https://github.com/mholt/caddy-l4/blob/31d74d38aa3a41c1563f25dfbee24ced3d4afae2/modules/l4proxy/proxy.go#L255-L256

## Better Solution

In the `nc` case, maybe we should call [TCPConn.CloseRead](https://pkg.go.dev/net#TCPConn.CloseRead) for all upstream connections between `io.Copy` and `wg.Wait():

```go
	// read from downstream until connection is closed;
	// TODO: this pumps the reader, but writing into discard is a weird way to do it; could be avoided if we used io.Pipe - see _gitignore/oldtee.go.txt
	io.Copy(ioutil.Discard, downTee)

	// Shut down the reading side of all upstream connections here

	// wait for reading from all upstream connections
	wg.Wait()
```

**Comment by mholt** [comment]
That is very nuanced. Thank you for the investigation and a solution. Really appreciate it!
