### ISSUE TITLE
Stuck trying to proxy DNS through a Wireguard tunnel

### ISSUE THREAD

**Issue by mindfuucker** [mholt/caddy-l4#42]
My setup has a VPS connected to my Homelab using Wireguard (10.14.0.1 <->10.14.0.6). In my homelab I have a DNS server on 192.168.1.59. I want to forward/proxy all DNS requests from 10.14.0.6 to the 192.168.1.59 device. After some fiddling around I got Caddy l4 working in Docker/Docker Compose and the [example http json file](https://caddy.community/t/writing-a-caddy-json-config-from-scratch/7524) works as intended. 

Calling `dig @10.14.0.6 google.com` from the Docker host or from the otherside of the tunnel results in a timeout: 
![image](https://user-images.githubusercontent.com/5075692/150694524-518fadb5-6560-4a8f-931b-3cb142dc2d92.png)
Docker seems to be exposing the port to the correct interface: 

![image](https://user-images.githubusercontent.com/5075692/150694695-65c80025-21b6-4572-99a0-446cafeb57c1.png)
What have I done wrong? Why is Caddy not proxy-ing the DNS request upstream to 192.168.1.59 ?

I have made the following Dockerfile:
```
FROM caddy:builder AS builder

RUN xcaddy build \
    --with github.com/mholt/caddy-l4

FROM caddy:latest

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile.json"]
```
And the following Docker Compose file:
```
version: "3.7"

services:
  caddy:
    build: .
    restart: unless-stopped
    ports:
      - "10.14.0.6:53:53"
    volumes:
      - ./caddy:/etc/caddy
```
And the folowing config file: ./caddy/Caddyfile.json
```
{
        "apps": {
                "layer4": {
                        "servers": {
                                "dns-example": {
                                        "listen": ["0.0.0.0:53"],
                                        "routes": [
                                                {
                                                        "handle": [
                                                                {
                                                                        "handler": "proxy",
                                                                        "proxy_protocol": "v2",
                                                                        "upstreams": [
                                                                                {"dial": ["192.168.1.59:53"]}
                                                                        ]
                                                                }
                                                        ]
                                                }
                                        ]
                                }
                        }
                }
        }
}
```
The container is able to reach 192.168.1.59 as I can ping the host from inside the container (exec).

**Comment by mholt** [comment]
DNS is UDP, right? The default network type is `tcp`: https://caddyserver.com/docs/conventions#network-addresses

**Comment by mindfuucker** [comment]
That seemed to fix it! 

Thanks for making this tool as I was contemplating Nginx stream, iptables rules or HAproxy when I found this. Configuring this seemed way more straightforward then the other stuff. 


![image](https://user-images.githubusercontent.com/5075692/150697559-5802d980-dd0e-426b-8c4c-0aee64f1b97e.png)


I wrongly assumed that unspecified would target both tcp and udp. 

New docker compose file:
```
....
    ports:
      - "10.14.0.6:53:53/udp"
....
```

new ./caddy/Caddyfile.conf:
```
  "listen": ["udp/0.0.0.0:53"],
  "routes": [
          {
                  "handle": [
                          {
                                  "handler": "proxy",
                                  "proxy_protocol": "v2",
                                  "upstreams": [
                                          {"dial": ["udp/192.168.1.59:53"]}
                                  ]
                          }
                  ]
          }
  ]
```

**Comment by mholt** [comment]
Yay. Looks great!
