### ISSUE TITLE
Default protocol type for listen addr `tcp/0.0.0.0:x` is `tcp6`

### ISSUE THREAD

**Issue by ghthor** [mholt/caddy-l4#47]
I've recently started using layer4 to perform some tcp proxying for ingress to some services. Currently our edge is accepting traffic with ipv4 addresses. My caddy file looks like the following.

```json
{
  "apps": {
    "layer4": {
      "servers": {
        "tcp": {
          "listen": ["tcp/0.0.0.0:1010"],
          "routes": [{
            "handle": [{
              "handler": "proxy",
              "proxy_protocol": "",
              "upstreams": [
                {"dial": ["tcp/${cluster_internal_ip}:1010"]}
              ]
            }]
          }]
        }
      }
    }
  }
}
```

You'll notice that my listener network addr is default `tcp` and provides the ipv4 catchall addr `0.0.0.0`. This configuration would lead me to believe that the socker should open on `tcp 0.0.0.0:1010` but what I've found is that it's opening on `tcp6 :::1010`.

```shell
~$ sudo netstat -plunt | grep 1010
tcp6       0      0 :::1010                 :::*                    LISTEN      13739/caddy-l4      
```

I'm noticing the same behavior on `Ubuntu 16.04.4 LTS` and `Ubuntu 18.04.5 LTS`. I have not checked on `Ubuntu 20.*`.

```shell
host1~$ uname -r -v && lsb_release -a 2>/dev/null | grep Desc
5.4.0-1038-aws #40~18.04.1-Ubuntu SMP Sat Feb 6 01:56:56 UTC 2021
Description:	Ubuntu 18.04.5 LTS
host2~$ uname -r -v && lsb_release -a 2>/dev/null | grep Desc
4.4.0-1128-aws #142-Ubuntu SMP Fri Apr 16 12:42:33 UTC 2021
Description:	Ubuntu 16.04.4 LTS
```

I'm running caddy with layer4 as a docker container using `--network-mode=host` from this [docker container][dockerhub] I've [created][gh]

[gh]: https://github.com/ghthor/caddy-l4-docker
[dockerhub]: https://hub.docker.com/r/ghthor/caddy-l4

**Comment by francislavoie** [comment]
You can use `tcp4/` to explicitly bind for IPv4 only, but `tcp/` will attempt to bind for both. These network types are defined by the Go stdlib: https://pkg.go.dev/net#Dial

**Comment by mholt** [comment]
I believe that behavior is set by the kernel if a tcp/ip version is unspecified and the address is ambiguous. (So I'm not particularly surprised in this case.)

**Comment by ghthor** [comment]
Ok, that all makes sense. I'm going to perform some tests to clarify that even when netstat is reporting `tcp6 :::1010` that caddy is still receiving ipv4 packets sent to the same port.

**Comment by ghthor** [comment]
Alright, I tested this and its accepting tcp4 traffic even when it netstat only lists it as tcp6. Guess this is a non issue, thanks for helping me settle this concern!

**Comment by RussellLuo** [comment]
There happens to be an issue here https://github.com/golang/go/issues/48723, which I think may be useful :)
