### ISSUE TITLE
PacketConn (udp) listener being closed by server handler 

### ISSUE THREAD

**Issue by jroyalty** [mholt/caddy-l4#53]
Once a handler chain completes (`echo` for instance), the server's PacketConn is closed when `handle()` returns.  Xref:  https://github.com/mholt/caddy-l4/blob/master/layer4/server.go#L97 ... This means the server will no longer accept incoming requests for this listener.  I see the server's PacketConn is wrapped in a `fakeClosePacketConn` but is destructed in this case since it's the last usage.  

I'm pretty sure this a logic error for datagram protocols at least?  And apologies, but I'm too inexperienced with this framework to suggest a fix at this point.

This can be reproduced using just the echo handler: 

```json
{
  "apps": {
    "layer4": {
      "servers": {
        "test": {
          "listen": ["udp/0.0.0.0:12345"],
          "routes": [
            {
              "handle": [{"handler": "echo"}]
            }
          ]
        }
      }
    }
  }
}
```
Then send any UDP traffic to port 12345.  I use `dig @localhost -p 12345 example.com`.  The first request will be echoed back (with warnings but that's beside the point) but subsequent requests will fail.

I'm able to reproduce this with caddy-l4@master using Caddy v2.4.6 and v2.5.0-beta.1.

**Comment by francislavoie** [comment]
The `echo` handler isn't really representative of how `caddy-l4` will work _overall_. It returns from `Handle()` as soon as it performs the copy, which causes the connection to close.

Try with `proxy` for example, you should notice that it doesn't close until the connection is actually done, I think, because it waits on the connections before returning from `Handle()`

**Comment by jroyalty** [comment]
I see how `echo` behaves correctly in the TCP sense because once the input is copied to the response, the handler's work is done and the server's side of the connection is closed.  However the server's listening socket remains active, as is expected, and further incoming connections are accepted.

In the UDP case, when server's side of the connection is closed that's actually closing the UDP listener so no new UDP connections can be accepted.  That's the logic error in the context of UDP.

**Comment by francislavoie** [comment]
Oh, yeah I see what you mean. `s.servePacket` calls `handle` with the actual `net.PacketConn`, whereas `s.serve` makes connections from the listener via `ln.Accept()` and closes those.

It seems to me like `handle` should take a boolean `shouldClose bool`, which is true when called in `s.serve` and false when called in `s.servePacket`. Probably all that needs to change.

Feel free to play around with it and make a PR if you like! I don't actually use layer4 myself, so it's best if someone else makes/tests the changes.

**Comment by francislavoie** [comment]
Alternatively, maybe "cleaner", `packetConn` in `server.go` could override `Close()` to ignore closing it?

**Comment by francislavoie** [comment]
Well, @jroyalty I opened #54, but I didn't try it out.

Could you build from that branch (you can do so by adding `@fix-udp` on your `--with` when building with `xcaddy` to target that PR's branch) and confirm it fixes the issue?

**Comment by jroyalty** [comment]
I commented on the PR, but this passes my test scenario.  Thanks for jumping on that!
