### ISSUE TITLE
Is there any way to match the destination host for SSH matcher ? 

### ISSUE THREAD

**Issue by sp4ke** [mholt/caddy-l4#57]
First, thank you very much for this amazing piece of code. 

I have multiple vhosts running on the proxy and one of them offers ssh access. For extra security I want to proxy ssh connection only when they match a specific host. How could I do that ?

**Comment by francislavoie** [comment]
It's not possible - the SSH protocol does not carry a hostname/server name. With HTTP, that's carried via the Host header or via TLS-SNI, but SSH has no equivalent.

**Comment by mholt** [comment]
Yeah, here's a discussion with some alternative ideas: https://serverfault.com/questions/34552/is-there-a-name-based-virtual-host-ssh-reverse-proxy
