### ISSUE TITLE
Whether this plug-in can implement SNI shunt？

### ISSUE THREAD

**Issue by lxhao61** [mholt/caddy-l4#6]
Whether this plug-in can implement SNI shunt, similar to nginx or haproxy SNI shunt.

**Comment by francislavoie** [comment]
What do you mean by "shunt"? Could you elaborate further exactly what behaviour you're looking for?

**Comment by lxhao61** [comment]
It is through this plug-in that different domain names can access different WEB servers.

**Comment by francislavoie** [comment]
You can do that with Caddy alone, you wouldn't need this plugin to do that.

```
site1.example.com {
	reverse_proxy 127.0.0.1:9001
}

site2.example.com {
	reverse_proxy 127.0.0.1:9002
}
```
