### ISSUE TITLE
How to load caddy.json ?

### ISSUE THREAD

**Issue by lucaspottersky** [mholt/caddy-l4#69]
**How to I make Caddy load the json file?** 

I am trying to run the [simple echo example.](https://github.com/mholt/caddy-l4#config-examples)

- xcaddy build --with github.com/mholt/caddy-l4
- created caddy.json
- ./caddy run

```
$ ./caddy run
2022/09/05 18:00:27.101 INFO    admin   admin endpoint started  {"address": "tcp/localhost:2019", "enforce_origin": false, "origins": ["//localhost:2019", "//[::1]:2019", "//127.0.0.1:2019"]}
2022/09/05 18:00:27.101 INFO    serving initial configuration
```

Sorry for the stupid question, but I can't seem to find docs about how to start a Caddy server that reads the `caddy.json` file. I'm new to Caddy.

**Comment by mholt** [comment]
`./caddy run --config caddy.json`

Caddy only loads config automatically if it's called `Caddyfile` (and it has to be in the Caddyfile format, which this module doesn't yet support).

**Comment by lucaspottersky** [comment]
thank you @mholt !
