### ISSUE TITLE
[Question] Versioning

### ISSUE THREAD

**Issue by aphilas** [mholt/caddy-l4#75]
I want to use caddy-l4 in docker.

The latest caddy-builder image on Docker Hub is [2.6.1](https://github.com/caddyserver/caddy-docker/blob/7f509065562f208807c67e0fb8dd9d28788b0d33/2.6/alpine/Dockerfile).

The Dockerfile
```Dockerfile
FROM caddy:2.6.1-builder-alpine AS builder

RUN xcaddy build \
    --with github.com/mholt/caddy-l4/layer4

FROM caddy:2.6.1-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```
fails with
```
#0 108.7 go: github.com/mholt/caddy-l4@v0.0.0-20220930194812-20fe2ab5fa71 (matching github.com/mholt/caddy-l4/layer4@upgrade) requires github.com/caddyserver/caddy/v2@v2.6.2-0.20220930193937-fe91de67b62c, not github.com/caddyserver/caddy/v2@v2.6.1
```
So the obvious solution is to build caddy manually.

I am following the steps on the [caddy readme](https://github.com/caddyserver/caddy#with-version-information-andor-plugins).

My main.go looks like this:
```go
import (
	// ...
	_ "github.com/caddyserver/caddy/v2/modules/standard"
	_ "github.com/mholt/caddy-l4"
)

// ...
```

On [master](https://github.com/mholt/caddy-l4/blob/master/go.mod#L8), caddy-l4 depends on caddy 2.6.2

`go get github.com/mholt/caddy-l4` yields
```
go: github.com/caddyserver/caddy/v2@v2.6.2: reading github.com/caddyserver/caddy/go.mod at revision v2.6.2: unknown revision v2.6.2
```
The latest release on caddy appears to be [2.6.1](https://github.com/caddyserver/caddy/tags)

There are no [tags/versions](https://github.com/mholt/caddy-l4/tags) on this repo either, and the [Caddy download](https://caddyserver.com/download?package=github.com%2Fmholt%2Fcaddy-l4) build with caddy-l4 fails.

I must admit, I don't have a clear picture of building go with specific commits/branches/tags of a repo, so I might need some pointers there.

Would you consider versioning this project?

~How can I build master (or a recent commit)?~

<details>
<summary>Environment</summary>

```
$ go version
go version go1.19 linux/amd64

$ uname -r
5.4.0-126-generic
```

</details>

---

ETA:

Deleting `github.com/caddyserver/caddy/v2` and `github.com/mholt/caddy-l4` from `go.mod` and then running `go get github.com/mholt/caddy-l4` followed by `go mod tidy` worked. I was still drafting this issue.

I will still leave this open in case someone is able to shed light on releases.

**Comment by mholt** [comment]
I had a bug in go.mod because I accidentally committed a `replace`. The fix was merged a couple hours ago while I was sleeping :upside_down_face:
