### ISSUE TITLE
Building caddy with caddy-l4 fails

### ISSUE THREAD

**Issue by ThisIsTenou** [mholt/caddy-l4#76]
Attempting to build the latest version of Caddy with caddy-l4 using [Caddy's download page](https://caddyserver.com/download) fails for at least Linux/amd64.

**Comment by mohammed90** [comment]
Pretty sure this is because caddy-l4 now depends on an unreleased/untagged (future) version of Caddy, so the builder refuses to upgrade Caddy because we received complaints when that happened before.

You can use xcaddy with the `master` argument to build from caddy's HEAD.

**Comment by MudDev** [comment]
I also cannot build, here is the error I get:

```
2022/10/11 22:21:24 [INFO] exec (timeout=0s): /usr/bin/go get -d -v github.com/mholt/caddy-l4@master github.com/caddyserver/caddy/v2
go: github.com/mholt/caddy-l4@master (v0.0.0-20221008133955-3a012bae82c7) requires github.com/caddyserver/caddy/v2@v2.6.2-0.20220930193937-fe91de67b62c, not github.com/caddyserver/caddy/v2@upgrade (v2.6.1)
2022/10/11 22:21:27 [FATAL] exit status 1
```

**Comment by MudDev** [comment]
Thanks @mohammed90 - specifying the **master** tag in the command worked.. For anyone else that runs into this, here is the command:

`xcaddy build --with github.com/mholt/caddy-l4 master`

**Comment by mholt** [comment]
Thanks for the follow-up.

That fix should only be needed temporarily; I'm hoping to release Caddy 2.6.2 this week and then I'll fix the go.mod files here and the problem should go away.

**Comment by jfmontanaro** [comment]
This problem seems to have reappeared, at least I'm getting the the same error when I try to build with the latest version of `caddy:builder` from Docker Hub:
````
go: github.com/mholt/caddy-l4@e788b8a (v0.0.0-20230728191639-e788b8a39708) requires github.com/caddyserver/caddy/v2@v2.7.0-beta.2.0.20230725185021-d7d16360d411, not github.com/caddyserver/caddy/v2@v2.6.4
```

I'm able to work around it for the time being by pinning to 38bd80163b43568cab5a12e09b41923bcac99f86. If I move forward to e788b8a39708f0f18cf63f88b7bb59ee6bbe728d I get the error again. Just thought I should drop a note here in case anyone else runs across this issue while searching that error.

**Comment by mohammed90** [comment]
> This problem seems to have reappeared, at least I'm getting the the same error when I try to build with the latest version of `caddy:builder` from Docker Hub:
> 
>     go: github.com/mholt/caddy-l4@e788b8a (v0.0.0-20230728191639-e788b8a39708) requires github.com/caddyserver/caddy/v2@v2.7.0-beta.2.0.20230725185021-d7d16360d411, not github.com/caddyserver/caddy/v2@v2.6.4
> 
> I'm able to work around it for the time being by pinning to 38bd80163b43568cab5a12e09b41923bcac99f86. If I move forward to e788b8a39708f0f18cf63f88b7bb59ee6bbe728d I get the error again. Just thought I should drop a note here in case anyone else runs across this issue while searching that error.

There are numerous factors and possibilities of why you're seeing this. Please create a new issue with the full details, not just that solo log line. Include the Dockerfile, how you're building the Docker image, and the commands you run.
