### ISSUE TITLE
An example configuration for "proxy all the raw bytes..."

### ISSUE THREAD

**Issue by count-null** [mholt/caddy-l4#81]
The readme suggests its possible to "Proxy all the raw bytes to 10.0.3.14:1592."
However, there doesn't seem to be an example which illustrates this. 

For my application, I would like to use caddy as a proxy for another device connected to the server via tailscale VPN. 

For example, my public server (has IP x.x.x.x) can access the device over local interface tailscale0 via 100.100.100.23. The device is listening for TCP/UDP stream on port 8888. I would like to proxy (pass-through) this port to the server. So public connections to x.x.x.x:8888 are no different than as if they were talking directly to the client on that port. 

Can you please provide an example JSON configuration which achieves this?

Here's what I've tried so far:

```
{"apps":{
"layer4": {
      "servers": {
        "udp": {
          "listen": ["udp/0.0.0.0:8888"],
          "routes": [{
            "handle": [{
              "handler": "proxy",
              "upstreams": [{
                "dial": ["100.100.100.23:8888"]
              }]
            }]
          }]
        }
      }
    }
  }
}
```

**Comment by mholt** [comment]
@count-null That should do it; note that your proxy is dialing TCP, is that what you intended? (Come to think of it I'm not sure I've tested proxying UDP -> TCP specifically, especially not over Tailscale.)

What doesn't work exactly? Can you post some logs? (Enable debug logging for more info)

**Comment by count-null** [comment]
This tailscale article mentions using `rinetd` for this purpose, it works better for me. Thanks
