### ISSUE TITLE
"Throttle data flow to simulate slow connections."

### ISSUE THREAD

**Issue by maclof** [mholt/caddy-l4#9]
Hey,

As per the subject, I am interested in adding some throttling to my routes to simulate slow connections

I am using this module to load balance connections for a game server

Is this currently possible? If not is it still a planned feature?

Thanks

**Comment by mholt** [comment]
Should be pretty easy to implement, you'd just have to use a rate limiter to control how fast reads/writes happen: https://pkg.go.dev/golang.org/x/time/rate

**Comment by mholt** [comment]
Ah what the heck, it was fun and easy so I went ahead and did it: https://github.com/mholt/caddy-l4/commit/6d4fcd2502341bd66a28fa9eac6dfe6e153930a7

So now there's a rate limited (throttled) handler. You can even configure a throttle across all connections, or per-connection, and latency too.

Example config:

```
{
	"logging": {
		"logs": {
			"default": {
				"level": "DEBUG"
			}
		}
	},
	"apps": {
		"layer4": {
			"servers": {
				"proxy": {
					"listen": ["127.0.0.1:1234"],
					"routes": [
						{
							"handle": [
								{
									"handler": "throttle",
									"read_bytes_per_second": 4,
									"read_burst_size": 2,
									"latency": "3s"
								},
								{
									"handler": "echo"
								}
							]
						}
					]
				}
			}
		}
	}
}
```

**Comment by maclof** [comment]
Woah dude, this is awesome!

I'll give it a try this evening :D
