### ISSUE TITLE
Caddyfile support?

### ISSUE THREAD

**Issue by IngwiePhoenix** [mholt/caddy-l4#90]
Just a quick question :)

I am looking at proxying my TVHeadend to the outside, so I will have to set up a proxy to it's RTSP as well. The HTTP one I am working on.

But, I configure all things Caddy using the Caddyfile syntax (I find it much easier to maintain when in a shell editor like nano or vim).

Can I use the l4 apps in a Caddyfile too?

Thanks and kind regards,
Ingwie

**Comment by IndeedNotJames** [comment]
Duplicate of #16

**Comment by mholt** [comment]
Yeah, I hear ya. It's not a small undertaking though. Would require several days worth of effort I think.
