### ISSUE TITLE
"selection_policies.ip_hash" should use same hashing algorithm as caddy

### ISSUE THREAD

**Issue by since1986** [mholt/caddy-l4#94]
In caddy, "ip_hash" uses the "Highest Random Weight" algorithm, but not in l4, which leads to the fact that the load balancing service used for both tcp layer 7 and layer 4 cannot obtain a consistent "upstream" through "ip_hash" ", which is **not** very good for some **stateful services** that require tcp layer 7 and layer 4 at the same time.

```go
// algorithm code in caddy

// hostByHashing returns an available host from pool based on a hashable string s.
func hostByHashing(pool []*Upstream, s string) *Upstream {
	// Highest Random Weight (HRW, or "Rendezvous") hashing,
	// guarantees stability when the list of upstreams changes;
	// see https://medium.com/i0exception/rendezvous-hashing-8c00e2fb58b0,
	// https://randorithms.com/2020/12/26/rendezvous-hashing.html,
	// and https://en.wikipedia.org/wiki/Rendezvous_hashing.
	var highestHash uint32
	var upstream *Upstream
	for _, up := range pool {
		if !up.Available() {
			continue
		}
		h := hash(up.String() + s) // important to hash key and server together
		if h > highestHash {
			highestHash = h
			upstream = up
		}
	}
	return upstream
}
```

```go
// algorithm code in l4

// hostByHashing returns an available host
// from pool based on a hashable string s.
func hostByHashing(pool []*Upstream, s string) *Upstream {
	poolLen := uint32(len(pool))
	if poolLen == 0 {
		return nil
	}
	index := hash(s) % poolLen
	for i := uint32(0); i < poolLen; i++ {
		index += i
		upstream := pool[index%poolLen]
		if upstream.available() {
			return upstream
		}
	}
	return nil
}
```

see [selectionpolicies.go](https://github.com/caddyserver/caddy/blob/7f2a93e6c36ceec9e007baeedeb594ab0dc43a71/modules/caddyhttp/reverseproxy/selectionpolicies.go#L519) and [loadbalancing.go](https://github.com/mholt/caddy-l4/blob/121f2ada24819cbb71e2aab1f6ab89e99d85fcf6/modules/l4proxy/loadbalancing.go#L319)

**Comment by francislavoie** [comment]
Ah yeah - the algorithm was updated in Caddy but it didn't make it here.

Feel free to open a PR to improve it!

**Comment by since1986** [comment]
> Ah yeah - the algorithm was updated in Caddy but it didn't make it here.
> 
> Feel free to open a PR to improve it!

I just looked at caddy's git history (Revision 026df7c5cb33331d223afc6a9599274e8c89dfd9), maybe caddy should keep the original version of the "ip_hash" algorithm as the "ip_hash" strategy, and the new version of the algorithm exists as a new strategy (such as " hwr_ip_hash", this way will be better.

**Comment by since1986** [comment]
Just post an issue to caddy
[https://github.com/caddyserver/caddy/issues/5340](https://github.com/caddyserver/caddy/issues/5340)

**Comment by mholt** [comment]
We should bring over Caddy's updated algorithm into this package. :+1:

**Comment by since1986** [comment]
> We should bring over Caddy's updated algorithm into this package. 👍

I added this function to the `Upstream` structure of l4 to adapt to the HWR algorithm. This function simply does a Join operation for the Dail of Upstream. 

I don’t know if this can meet the requirements of the HWR algorithm. I checked the HWR algorithm According to the information, I generally understand that the HWR algorithm needs to hash the server's identity and key together (I don't know if I understand it right?), this identity should have no special requirements, so I used a simple `Join` to generate it One.

```go

...

// added this function to l4's Upstream structure to adapt to the HWR algorithm
func (u Upstream) String() string {
	return strings.Join(u.Dial, ",")
}

...

```

```go
func hostByHashing(pool []*Upstream, s string) *Upstream {
	// HWR hash (copy from caddy's code)
	var highestHash uint32
	var upstream *Upstream
	for _, up := range pool {
		if !up.available() {
			continue
		}
		h := hash(up.String() + s) // important to hash key and server together
		if h > highestHash {
			highestHash = h
			upstream = up
		}
	}
	return upstream
}
```

**Comment by since1986** [comment]
After reading  [this article](https://randorithms.com/2020/12/26/rendezvous-hashing.html), I feel that the general understanding of the HRW algorithm, its key points are: first, for each key to say that there is more than one server candidate, the second, for each key to say that the server candidate list is guaranteed to be as different as possible. The first point ensures that a server drop does not trigger a full re-hash, and the second point ensures that there will not be a full re-hash caused by the extreme case where all the first candidates of the key are the same.
