### ISSUE TITLE
Pass remote IP via L4 to http app?

### ISSUE THREAD

**Issue by t0th0mas** [mholt/caddy-l4#97]
Is there any chance to pass the conections remote IP via L4 to a Caddy HTTP app?

I mean:
[CLIENT] -> Caddy L4 -> Caddy HTTP app -> Webserver -> REMOTE_ADDR/X-FORWARDED-FOR header

**Comment by francislavoie** [comment]
Yes, with the PROXY protocol. On the l4 side you configure the proxy handler to send proxy protocol. On the HTTP side you'll need to use a listener wrapper plugin.

**Comment by IndeedNotJames** [comment]
Just be aware that http/3 won't be able to work that way, due to http/3 being udp, while the PROXY protocol is tcp only.
So you may want to disable http/3 for your http server if you decide to go down that route.

**Comment by t0th0mas** [comment]
> Yes, with the PROXY protocol. See the README. On the l4 side you configure the proxy handler to send proxy protocol. On the HTTP side you'll need to use a listener wrapper plugin.

I tried as you suggested, but now getting "ERROR   layer4  handling connection     {"remote": "123.123.123.123:55444", "error": "parsing the PROXY header: invalid signature"}"

**L4 APP:**
```
{
  "match": [
	{
	  "http": [
		{
		  "host": [
			"host.example.com"
		  ]
		}
	  ]
	}
  ],
  "handle": [
	{
		"handler": "proxy_protocol"
	},
	{
	  "handler": "proxy",
	  "proxy_protocol": "v2",
	  "upstreams": [
		{
		  "dial": [
			"localhost:8085"
		  ]
		}
	  ]
	}
  ]
}
```

**HTTP APP:**
```
"http": {
  "servers": {
	"static": {
	  "listener_wrappers": [
		{
		  "wrapper": "proxy_protocol",
		  "timeout": "5s",
		  "allow": [
			"0.0.0.0/0"
		  ]
		}
	  ],
	  "listen": [
		"0.0.0.0:8085"
	  ],
	  "protocols": [
		"h1",
		"h2"
	  ],
	  "routes": [
		{
		  "handle": [
			{
			  "handler": "reverse_proxy",
			  "upstreams": [
				{
				  "dial": "192.168.1.1:80"
				}
			  ]
			}
		  ]
		}
	  ]
	}
  }
}
```

**Comment by IndeedNotJames** [comment]
Try removing the `proxy_protocol` handler from your l4
```diff
	}
  ],
  "handle": [
-	{
-		"handler": "proxy_protocol"
-	},
	{
	  "handler": "proxy",
	  "proxy_protocol": "v2",
```

**Comment by t0th0mas** [comment]
> Try removing the `proxy_protocol` handler from your l4

**After removing Caddy throws folllowing error:**
2023/02/21 20:50:58.157 ERROR   layer4.handlers.proxy   upstream connection     {"local_address": "[::1]:41878", "remote_address": "[::1]:8085", "error": "read tcp [::1]:41878->[::1]:8085: read: connection reset by peer"}

Response in browser is _400 Bad Request_

**Comment by francislavoie** [comment]
To clarify, the original client doesn't use proxy protocol so you should not use the handler at the edge. You should only add proxy protocol to the l4 proxy and to the HTTP app listener wrapper.

**Comment by francislavoie** [comment]
That's probably fine. What's in your HTTP app's logs? Enable debug level logging.

**Comment by t0th0mas** [comment]
Hmmm, I changed localhost to 127.0.0.1 and it worked:

```
          "upstreams": [
            {
              "dial": [
                "127.0.0.1:8085"
              ]
            }
          ]
```
