### ISSUE TITLE
Question: SSH Proxy + optional proxy auth

### ISSUE THREAD

**Issue by waldauf** [mholt/caddy-l4#98]
Hello,

(1). I'm trying to set SSH proxy over Caddy but can't the proper configuration. I would like to set Caddy listening on port 2222 and proxy SSH connection to the port home_server:22. Can I ask you for help?

This is my configuration:
```
{
    "apps": {
        "layer4": {
            "servers": {
              "ssh-gitea": {
                "listen": [":2222"],
                "routes": [
                  {
                    "match": [
                      {
                        "ssh": []
                      }
                    ],
                    "handle": [
                      {
                        "handler": "proxy",
                        "upstreams": [
                          {"dial": ["localhost:22"]}
                        ]
                      }
                    ]
                  }
                ]
              }
            }
        }
    }
}
```

Output in log:
```
❯ ./caddy run --config caddyfile.json
2023/02/28 22:44:31.743 INFO    using provided configuration    {"config_file": "caddyfile.json", "config_adapter": ""}
2023/02/28 22:44:31.745 INFO    admin   admin endpoint started  {"address": "localhost:2019", "enforce_origin": false, "origins": ["//localhost:2019", "//[::1]:2019", "//127.0.0.1:2019"]}
Error: loading initial config: loading new config: loading layer4 app module: provision layer4: server 'ssh-gitea': route 0: loading matcher modules: module name 'ssh': decoding module config: layer4.matchers.ssh: json: cannot unmarshal array into Go value of type l4ssh.MatchSSH
```
Why do I see opened port 2019 if it's not configured?

(2). Is there an option for how to enable proxy credentials to use this SSH proxy?

EDIT: Fixed typos

**Comment by mohammed90** [comment]
You should use `{}` to configure/enable the ssh matcher, not `[]`.

```diff
{
    "apps": {
        "layer4": {
            "servers": {
              "ssh-gitea": {
                "listen": [":2222"],
                "routes": [
                  {
                    "match": [
                      {
-                        "ssh": []
+                        "ssh": {}
                      }
                    ],
                    "handle": [
                      {
                        "handler": "proxy",
                        "upstreams": [
                          {"dial": ["localhost:22"]}
                        ]
                      }
                    ]
                  }
                ]
              }
            }
        }
    }
}
```

> Why do I see opened port 2019 if it's not configured?

Caddy exposes an administration API on `localhost:2019` to allow for graceful reloads and shutdown, amongst others. You can read about it [here](https://caddyserver.com/docs/api).

> (2). Is there an option for how to enable proxy credentials to use this SSH proxy?

The `proxy` handler will proxy the raw bytes without manipulation. The authentication is still handled by the upstream server, i.e. `localhost:22`.

**Comment by waldauf** [comment]
Thank you very much for your help. It was a foolish mistake. How I should know when to use `[]` and when `{}` brackets?

**Comment by mohammed90** [comment]
> How I should know when to use [] and when {} brackets?

The documentation shows the `{}` here

https://caddyserver.com/docs/json/apps/layer4/servers/routes/match/ssh/
